### ISSUE TITLE
Test Failures for OpenMP & OpenMPTarget Need Investigation

### ISSUE THREAD

**Issue by rchen20** [LLNL/RAJA#1005]
These tests fail when running either OpenMP or OpenMPTarget, built with xl/2021.01.08. The root causes are not patently clear and need further investigation.

Strongly type index seg faults:
test-forall-ListSegment-OpenMPTarget
test-forall-RangeSegment-OpenMPTarget
test-forall-RangeStrideSegment-OpenMPTarget
test-forall-resource-ListSegment-OpenMPTarget
test-forall-resource-RangeSegment-OpenMPTarget
test-forall-resource-RangeStrideSegment-OpenMPTarget

Illegal warp address in forall:
test-forall-basic-ReduceSum-OpenMPTarget
test-kernel-tile-Fixed2D-OpenMPTarget (warp out of range address)

Seg fault with View of work_array:
test-kernel-nested-loop-MultiLambda-OpenMP
test-kernel-nested-loop-MultiLambdaParam-OpenMP
test-kernel-tile-Fixed2D-OpenMP
test-kernel-tile-Dynamic2D-OpenMP

Seg fault during array initialization forall:
test-forall-AtomicView-OpenMPTarget (works when initializing on host array with memcpy)
test-forall-AtomicRefAdd-OpenMPTarget
test-forall-AtomicRefCAS-OpenMPTarget

Unknown seg faults:
test-kernel-basic-single-loop-Segments-OpenMP
test-kernel-basic-single-loop-Segments-OpenMPTarget (not seg faulting, but produces wrong answers)
test-kernel-nested-loop-Basic-OpenMP (seg faults somewhere, also wrong answers)
test-kernel-nested-loop-segments-OpenMP

Not yet classified seg faults:
test-workgroup-Unordered-Single-OpenMPTarget
test-workgroup-Unordered-MultipleReuse-OpenMPTarget
test-workgroup-Enqueue-Single-OpenMPTarget
test-workgroup-Enqueue-Multiple-OpenMPTarget
test-kernel
test-sharedmem
test-simd

**Comment by brandonneth** [comment]
On Lassen, with XL 2021.03.11-cuda-11.2.0, I was able to reproduce the issue for: 

test-forall-ListSegment-OpenMPTarget
test-forall-RangeSegment-OpenMPTarget
test-forall-RangeStrideSegment-OpenMPTarget
test-forall-resource-ListSegment-OpenMPTarget
test-forall-resource-RangeSegment-OpenMPTarget
test-forall-resource-RangeStrideSegment-OpenMPTarget
test-forall-basic-ReduceSum-OpenMPTarget
test-forall-AtomicRefAdd-OpenMPTarget
test-forall-AtomicRefCAS-OpenMPTarget
test-workgroup-Unordered-Single-OpenMPTarget
test-workgroup-Unordered-MultipleReuse-OpenMPTarget


The following tests passed:
test-kernel-basic-single-loop-Segments-OpenMP
test-kernel-basic-single-loop-Segments-OpenMPTarget
test-kernel-nested-loop-Basic-OpenMP
test-kernel-nested-loop-segments-OpenMP
test-kernel
test-sharedmem
test-simd

My build couldn't find make commands for:
test-workgroup-Enqueue-Single-OpenMPTarget
test-workgroup-Enqueue-Multiple-OpenMPTarget
test-forall-AtomicView-OpenMPTarget

I'm going to start from the top with:
test-forall-ListSegment-OpenMPTarget
test-forall-RangeSegment-OpenMPTarget
test-forall-RangeStrideSegment-OpenMPTarget

**Comment by brandonneth** [comment]
For tests-forall-RangeSegment-OpenMPTarget, I've discovered the following:

The test allocates `working_array` using an Omp resource, so it makes a call to omp_target_alloc. This pointer to device data is then captured by the lambda that is passed to the forall call. While this is a device pointer, arrays that are captured by lambdas are treated as if they were mapped with zero length. From the openmp spec:

"the variables that are of pointer type are treated as if they had appeared in a map clause as zero-length array sections;"
https://www.openmp.org/spec-html/5.0/openmpsu109.html

If I run the equivalent loop with the is_device_ptr(working_array) clause, the execution goes fine. So far, I can't find a way to include that is_device_ptr clause within the RAJA::forall way of running it.

**Comment by rchen20** [comment]
Current results with updated compilers:

xl/2021.09.22 - 100% pass

clang/ibm-12.0.1 - 2 failures
    test-algorithm-sort-OpenMP.exe (SEGFAULT)
    test-algorithm-stable-sort-OpenMP.exe (SEGFAULT)

clang/12.0.1 - 100% pass

**Comment by rhornung67** [comment]
That looks right. Thanks @rchen20 @MrBurmark I've seen OMP sort test failures with IBM compilers. Do these look familiar to you?

**Comment by rhornung67** [comment]
@rchen20 can we close this issue?

**Comment by rchen20** [comment]
@MrBurmark said that he has seen these sort failures before, so I'll close the issue.
