### ISSUE TITLE
Possible Clang-IBM OpenMP Target Runtime Error 

### ISSUE THREAD

**Issue by rchen20** [LLNL/RAJA#1056]
`test-forall-AtomicMultiView-OpenMPTarget` fails for `long` types due to a mapping error at runtime, with the `clang-ibm-10.0.1-gcc-8.3.1_omptarget` compiler. This test works when using `clang-10.0.1-gcc-8.3.1_omptarget`. LC states that the difference between clang and clang-ibm is the runtime, so we suspect an error there.

**Comment by rhornung67** [comment]
@rchen20 can this issue be closed?

**Comment by rchen20** [comment]
Yes, this worked with updated compilers from IBM, so I'll close it.
