### ISSUE TITLE
update RAJA proxy repo after v0.14.0 release

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1066]
Update RAJA proxy repo to v0.14.0 version of RAJA after the v0.14.0 release and make sure everything builds and runs.

https://github.com/LLNL/RAJAProxies

@kab163 do you want to take a swing at this to get more familiar with RAJA and how it is used in codes?

**Comment by kab163** [comment]
> @kab163 do you want to take a swing at this to get more familiar with RAJA and how it is used in codes?

Sure, sounds good!

**Comment by rhornung67** [comment]
If it's not simple and straightforward, it's @davidbeckingsale 's fault :-)

**Comment by rhornung67** [comment]
@rchen20 this issue can be closed, correct? If so, please do that.
