### ISSUE TITLE
Move RAJA proxy app repo to GitHub

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#107]

**Comment by willkill07** [comment]
I believe this is done (See: https://github.com/llnl/raja-examples)

**Comment by davidbeckingsale** [comment]
Correct!

Cheers,
--David

---
David Beckingsale, david@llnl.gov, people.llnl.gov/david
Center for Applied Scientific Computing @ Lawrence Livermore National 
Laboratory
