### ISSUE TITLE
cuda_exec execution policy does not have default template argument

### ISSUE THREAD

**Issue by mlohry** [LLNL/RAJA#1072]
Not sure if this is a code bug or doc bug. [Documentation](https://raja.readthedocs.io/en/main/tutorial/add_vectors.html) states

> The thread block size parameter is optional; if not provided, the RAJA policy provides a default of 256, which is a reasonable choice for most cases.

but a forall like

```
  RAJA::forall<RAJA::cuda_exec<>>(RAJA::RangeSegment(0, N), 
    [=] RAJA_DEVICE (int i) { 
    c[i] = a[i] + b[i]; 
  }); 
```

fails with error: too few arguments for class template "RAJA::policy::cuda::cuda_exec"

**Comment by rhornung67** [comment]
@mlohry thanks for pointing that out. It's a doc bug. We used to provide a default thread block size, but no longer do that. I will fix it.

**Comment by mlohry** [comment]
Thanks, doc bug is also in the PDFs FYI.

Related, how is the grid size determined then? I just ran a basic test with `RAJA::cuda_exec<256>;` and looking at nvidia nsight profiling this ended up with a `grid <<<1,1,1>>>` and `block <<<256,1,1>>>`.

**Comment by artv3** [comment]
Its depends on the number of threads per block and the size of the iteration space: 
Calculated like this:
```
 cuda_dim_member_t gridSize = (len + block_size - 1) / block_size; 
```
