### ISSUE TITLE
Missing Table in Reduction Docs

### ISSUE THREAD

**Issue by brandonneth** [LLNL/RAJA#1084]
Within the Reduction Policies section found here: https://raja.readthedocs.io/en/main/feature/policies.html#reducepolicy-label
The text says "The following table summarizes RAJA reduction policy types:" but then there is no table.

**Comment by rhornung67** [comment]
There was a bug in the table in the rst file. It is fixed here: https://raja.readthedocs.io/en/v0.14.0-rc/sphinx/user_guide/feature/policies.html

**Comment by rhornung67** [comment]
FIx included in v0.14.0 docs
