### ISSUE TITLE
Missing unit tests for atomics

### ISSUE THREAD

**Issue by JohnHynes** [LLNL/RAJA#1090]
Related to the feature/desul-atomics PR found here: https://github.com/LLNL/RAJA/pull/1073

Some supported atomics are only tested in integration tests, but lack their own independent unit tests. Most notably, the cuda-like increment/decrement functions which wrap upon reaching a given value.

Atomics not tested:
- https://github.com/LLNL/RAJA/blob/b11afe2e7ab125cca54e547026bf9529562c5329/include/RAJA/policy/atomic_builtin.hpp#L297
- https://github.com/LLNL/RAJA/blob/b11afe2e7ab125cca54e547026bf9529562c5329/include/RAJA/policy/atomic_builtin.hpp#L311

Atomic Unit Tests: https://github.com/LLNL/RAJA/tree/develop/test/unit/atomic

**Comment by rhornung67** [comment]
@JohnHynes this is done in your branch, correct?

**Comment by JohnHynes** [comment]
@rhornung67 This is done in https://github.com/LLNL/RAJA/pull/1073

**Comment by rhornung67** [comment]
Thanks. Please close the issue if you no longer need it.
