### ISSUE TITLE
OpenMP Target Build Issue

### ISSUE THREAD

**Issue by brandonneth** [LLNL/RAJA#1092]
When building with OpenMP and Offloading enabled, test-kernel-basic-single-loop-Segments-OpenMPTarget.exe (and others) are hitting errors bc of a missing forall_impl implementation.

I've run into the issue with XL 16.01 and Clang 11.0.1, both on Lassen.

**Steps to Reproduce**
```
mkdir build
cd build
cmake -DENABLE_OPENMP=On -DENABLE_TARGET_OPENMP=On ..
make test-kernel-basic-single-loop-Segments-OpenMPTarget.exe
```

It looks like the problem is that the kernel call is using a Host resource, while the available omp_target forall_impls all expect a Omp resource.

**Fix**

adding the following to include/RAJA/policy/openmp_target/forall.hpp fixes the issue for me. All I did was copy the existing implementation and change the return and first argument's type (and name) from resources::Omp to resources::Host.

```
template <typename Iterable, typename Func>
RAJA_INLINE resources::EventProxy<resources::Host> forall_impl(resources::Host host_res,
                                                              const omp_target_parallel_for_exec_nt&,
                                                              Iterable&& iter,
                                                              Func&& loop_body)
{
  using Body = typename std::remove_reference<decltype(loop_body)>::type;
  Body body = loop_body;

  RAJA_EXTRACT_BED_IT(iter);

#pragma omp target teams distribute parallel for schedule(static, 1) \
    firstprivate(body,begin_it)
  for (decltype(distance_it) i = 0; i < distance_it; ++i) {
    Body ib = body;
    ib(begin_it[i]);
  }

  return resources::EventProxy<resources::Host>(host_res);
}
```

**Comment by liruipeng** [comment]
@brandonneth I have similar issue

```
In file included from /usr/WS1/li50/RAJA-git/raja/build_lc_blueos-xl_2020.09.17_omptarget/test/functional/forall/indexset/test-forall-IcountIndexSet-OpenMPTarget.cpp:11:
In file included from /usr/WS1/li50/RAJA-git/raja/test/include/RAJA_test-base.hpp:15:
In file included from /usr/WS1/li50/RAJA-git/raja/include/RAJA/RAJA.hpp:44:
/usr/WS1/li50/RAJA-git/raja/include/RAJA/pattern/forall.hpp:197:10: error: no matching function for call to 'forall_impl'
  return forall_impl(r, std::forward<ExecutionPolicy>(p), range, adapted);
```

**Comment by brandonneth** [comment]
get_resource_from_platform unimplemented for omp_target and omp_target policies didn't have platform information. Adding those two things, specifics to come, fixes this

**Comment by brandonneth** [comment]
Similar problem appears with the nested kernels, however the solution for the 1d case does not work here. I think it is because there are two different exec policies in the KernelPolicy (seq and omp_target_blah), so the nested forall_impl calls actually need to have different resources passed to them instead of the resource thats stored with the LoopData.
