### ISSUE TITLE
Reorganize header files for flexible policy selection

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#110]
Currently, we encourage users to include a single RAJA header file in their applications, which pulls in all of RAJA functionality that is enabled.  We need to break this apart into a sensible scheme that enables users to clearly see how to include only the parts of RAJA that they need. For example, if they only want to use CUDA, they should be able to only include RAJA-CUDA support via a single header file and ignore all the rest (e.g., OpenMP, etc.).

We've started to discuss this on our Confluence page, but it requires group discussion to full flesh out.

Also, this should be done after the execution policy PR is merged.

**Comment by davidbeckingsale** [comment]
See #139

**Comment by davidbeckingsale** [comment]
Fixed in #221.
