### ISSUE TITLE
Make external camp default configuration

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1110]
When compiling an application with both RAJA and Umpire, the version of camp used depends on the order of '-l' flags setting the paths to RAJA and Umpire headers. This can cause problems when testing an update of one library without changing the other.

Since most app users manage camp as a separate TPL and point RAJA, Umpire, etc. at that, we should make this the default configuration following a pattern similar to what we now do for CUB and rocprim.

@davidbeckingsale has a PR to update RAJA CI to use an external camp install (via Spack) so we make sure to test this. The PR is here: https://github.com/LLNL/RAJA/pull/1109

**Comment by rhornung67** [comment]
@davidbeckingsale can this issue be closed since the PR mentioned above has been merged?

**Comment by davidbeckingsale** [comment]
I don't think this is the "default" configuration, but it is now tested via CI.

**Comment by rhornung67** [comment]
Do you think the CI testing is sufficient, or should we change the cmake logic?

**Comment by davidbeckingsale** [comment]
I think it's good in CI, and we should keep the current CMake logic so it's still easy to build with the camp submodule. We can start to suggest to users that they should build against a single external camp when using RAJA/CHAI/Umpire.

**Comment by rhornung67** [comment]
So close the issue, or more work to do on this?

**Comment by davidbeckingsale** [comment]
Close.
