### ISSUE TITLE
Imrpove error handling for adding segments to IndexSet

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#114]
Currently, if one attempts to add an invalid segment type to an IndexSet, the code silently ignores the segment and doesn't add it. This should be reported as a warning, halt the code, or whatever mechanism we choose to help users understand anomalous usage.

Note: the whole 'valid segment' concept may go away in the future when we improve  the implementation of IndexSet. Nevertheless, it is an issue now.

**Comment by davidbeckingsale** [comment]
Fixed by #234
