### ISSUE TITLE
Wrong rocprim version used with scripts

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#1140]
When using our scripts and explicitly using a rocm/hip version the wrong rocprim version will be used if a different rocm module is loaded. This happens because FindRocPRIM.cmake uses the cmake function find_path which searches the ENV var CMAKE_PREFIX set by the module before looking at our HINTS.

**Comment by rhornung67** [comment]
@MrBurmark has this been fixed?

**Comment by MrBurmark** [comment]
Not yet.
