### ISSUE TITLE
Finish BoxSegment branch and merge

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#115]
Issues to address:
- [ ] Correctness checking (via static_assert, etc.)
- [ ] Documentation and example usage
- [ ] Unit tests

**Comment by trws** [comment]
Possibly also address the fact that it's incomplete and/or broken...
Iteration over "m_dim," runtime user-supplied number of dimensions [here](https://github.com/LLNL/RAJA/blob/feature/keasler/BoxSegment/include/RAJA/BoxSegment.hxx#L69)
fixed_size backing store of length 3 [here](https://github.com/LLNL/RAJA/blob/feature/keasler/BoxSegment/include/RAJA/BoxSegment.hxx#L254)
empty block where code for 3-dimensional BoxSegments would be handled [here](https://github.com/LLNL/RAJA/blob/feature/keasler/BoxSegment/include/RAJA/exec-openmp/forall_openmp.hxx#L513)...
