### ISSUE TITLE
Updates to hip configs

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#1156]
Add `-lamd_comgr` to host config for HIP 4.5. https://github.com/LLNL/RAJA/blob/develop/host-configs/lc-builds/toss3/hip_link_X.cmake

This may have to be done in blt, but set `HIP_CLANG_FLAGS` instead of `HIP_HIPCC_FLAGS` to `--offload-arch=gfx908` as this flag is currently not making it to the compile line.

Add `-mllvm -amdgpu-fixed-function-abi=1` to `HIP_CLANG_FLAGS` to get hip workgroup/kernel fusion working with HIP 4.5.

These also apply to RAJAPerf.

**Comment by rhornung67** [comment]
@MrBurmark should we add these things to the hip host config/build script?

**Comment by MrBurmark** [comment]
Yes, this has not been done yet.
