### ISSUE TITLE
Develop OpenMP 4.5 backend

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#116]
Now that we have a viable clang compiler for this, build an OpenMP 4.5 backend to be able to compare performance, etc. Tasks include:
- [x] traversals and policies
- [x] reductions
- [ ] unit tests

**Comment by willkill07** [comment]
I'm going to close this.

We have two unit tests that were merged as part of #255 . As we add additional functionality, we can add more unit tests.

**Comment by davidbeckingsale** [comment]
Thanks! I think we closed out the JIRA ticket and forgot this one.
