### ISSUE TITLE
Double "RAJA_RAJA_" header prefix?

### ISSUE THREAD

**Issue by rchen20** [LLNL/RAJA#1160]
Was this intended to be a double header prefix?

https://github.com/LLNL/RAJA/blob/122fa519ebc84f1ed114b70444fb807bd8e4efa9/include/RAJA/pattern/detail/reduce.hpp#L59

**Comment by rhornung67** [comment]
Nope. That is clearly wrong. Do you have time to check through the code for these, fix them and put up a PR?

**Comment by rchen20** [comment]
Yes, there should only be 2 instances of this. Found these as I'm trying to address the CAMP omp target missing resource::omp problem.

**Comment by rhornung67** [comment]
Thank you for digging into this.  There was a recent change to camp to add missing guards. Did that fix anything for RAJA?

**Comment by rchen20** [comment]
The latest CAMP/main is still not picking up `-DENABLE_TARGET_OPENMP`. I'm checking the c++14 branch to see if it is fixed there.
