### ISSUE TITLE
OffsetLayout Constructor

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#1173]
The OffsetLayout constructor takes inclusive bounds [first last] instead of [begin, end) which is used elsewhere.

**Comment by artv3** [comment]
This is awesome, but this could be a code-breaking change. When this gets merged we will have to give folks a heads up.

**Comment by rhornung67** [comment]
> This is awesome, but this could be a code-breaking change. When this gets merged we will have to give folks a heads up.

RIght. I will make that clear in the release notes. I think this is an improvement since now everything is consistent.
