### ISSUE TITLE
Update Gitlab compiler specs

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1187]
**NOTE: The compilers and versions below is just a sketch of what we may want to have. We will coordinate with the RADIUSS effort and @davidbeckingsale 's compiler list for llnl wsc applications.**

These changes will require changes to:

- [ ] RADIUSS spack configs, include a PR to that repo.
- [ ] RAJA/.gitlab/*jobs.yml files.
- [ ] RAJA spack package, possibly.

For lassen:

- [ ] Add a mix of newer clang and clang-ibm compilers. Remove clang9 and older jobs.
- [ ] Replace XL jobs with new compiler versions. Remove 2021.03.x and older jobs.
- [ ] Replace all CUDA jobs, update to CUDA 10.2.89 and newer, including CUDA 11. Remove CUDA 10.1.x and older jobs.

For ruby:

- [ ] Remove clang9 and older jobs. Add newer clang versions (10, 11, 12, 13)
- [ ] Add gnu9 and gnu10 jobs. Keep gnu8.
- [ ] Add intel 2021 (latest) job, remove intel18?
- [ ] Add intel oneAPI job

For corona:

- [ ] Update rocm versions. Include a mix of 4.3 and 4.5.
- [ ] Remove clang9 and older jobs. Replace with clang 11, 12, 13.
- [ ] Add gnu9 and gnu10 versions. Keep gnu8.

Add a testing pipeline on El Capitan EA systems:

- [ ] Currently, rznevada is on the RZ so it can't be driven directly from GitHub. But, nighlty scheduled testing will be a good start.

**Comment by rhornung67** [comment]
@davidbeckingsale what do you think?

**Comment by davidbeckingsale** [comment]
This looks good, and I think most of it is covered by the set of compilers I'm adding to the radiuss-configs.

**Comment by rhornung67** [comment]
Outdated.
