### ISSUE TITLE
Scan exclusive compile error

### ISSUE THREAD

**Issue by mclarsen** [LLNL/RAJA#1191]
Current raja release. I am using llvm clang 13.0.0 with serial, openmp and cuda configured. This only happens with the `RAJA::seq_exec`.
Anyone seen this before:

```
raja/include/RAJA/policy/sequential/scan.hpp(157): error: expression must be a modifiable lvalue
          detected during:
            instantiation of "camp::concepts::enable_if_t<camp::resources::v1::EventProxy<camp::resources::v1::Host>, RAJA::type_traits::is_sequential_policy<ExecPolicy>> RAJA::impl::scan::exclusive(camp::resources::v1::Host, const ExecPolicy &, Iter, Iter, OutIter, BinFn, T) [with ExecPolicy=luminary::vis::SerialExec::for_policy, Iter=const luminary::vis::Id *, OutIter=luminary::vis::Id *, BinFn=RAJA::operators::plus<luminary::vis::Id, luminary::vis::Id, luminary::vis::Id>, T=luminary::vis::Id]" 
/home/mclarsen/.cache/bazel/_bazel_mclarsen/bdd0657b05cd1ca06a9a049087540106/external/raja/include/RAJA/pattern/scan.hpp(292): here
            instantiation of "camp::concepts::enable_if_t<camp::resources::v1::EventProxy<Res>, RAJA::type_traits::is_execution_policy<ExecPolicy>, RAJA::type_traits::is_resource<Res>, std::is_constructible<camp::resources::v1::Resource, Res>, camp::type_traits::is_range<InContainer>, camp::type_traits::is_range<OutContainer>> RAJA::policy_by_value_interface::exclusive_scan(ExecPolicy &&, Res, InContainer &&, OutContainer &&, Function, T) [with ExecPolicy=luminary::vis::SerialExec::for_policy, Res=camp::resources::v1::Host, InContainer=RAJA::Span<const luminary::vis::Id *, luminary::vis::Id>, OutContainer=RAJA::Span<luminary::vis::Id *, luminary::vis::Id>, T=luminary::vis::Id, Function=RAJA::operators::plus<luminary::vis::Id, luminary::vis::Id, luminary::vis::Id>]"
```

I have the distinct feeling that I have seen this before, but I couldn't find any issues relating to this.

**Comment by mclarsen** [comment]
Ok. Figured it out, but it still confuses me. Original code:

```
template <typename Exec>
Array<Id> Offsets(const Array<Id>& counts, Exec) {
  constexpr MemSpace mem_space = Exec::mem_space;
  using for_policy = typename Exec::for_policy;

  const Id size = counts.Size();
  const Id* counts_ptr = counts.Ptr(mem_space);

  Array<Id> offsets;
  offsets.Resize(size);
  Id* offsets_ptr = offsets.Ptr(mem_space);
  RAJA::exclusive_scan<for_policy>(RAJA::make_span(counts_ptr, size),
                                   RAJA::make_span(offsets_ptr, size),
                                   RAJA::operators::plus<Id>{});
  return offsets;
}
```

Code that compiles:

```
template <typename Exec>
Array<Id> Offsets(Array<Id>& counts, Exec) {
  constexpr MemSpace mem_space = Exec::mem_space;
  using for_policy = typename Exec::for_policy;

  const Id size = counts.Size();
  Id* counts_ptr = counts.Ptr(mem_space);

  Array<Id> offsets;
  offsets.Resize(size);
  Id* offsets_ptr = offsets.Ptr(mem_space);
  RAJA::exclusive_scan<for_policy>(RAJA::make_span(counts_ptr, size),
                                   RAJA::make_span(offsets_ptr, size),
                                   RAJA::operators::plus<Id>{});
  return offsets;
}

```

The difference is the `const Id *`. Not sure why this works with cuda but not with the serial exec.

**Comment by rhornung67** [comment]
@mclarsen that user seems familiar, but I can't recall who he is..... 😄 

Anyway, that is strange. I verified that all our tests build and run with clang 13, but none of them pass a const ptr to make_span(). There should be no dependencies between the array data and the exec policy. Moreover, here counts_ptr is the input data and so it should work if it is const ptr.  I'll mess around with it and see if I can reproduce.  Thanks for reporting (or sending me on a wild goose chase?)

**Comment by mclarsen** [comment]
Life and compilation is confusing. At least it should be easy to reproduce.

**Comment by rhornung67** [comment]
@MrBurmark i've verified locally that Matt's issue is reproducible across multiple versions of clang and gnu compilers. Echoing @mclarsen , why does this work for cuda but not sequential? Any ideas?

**Comment by MrBurmark** [comment]
The implementation is different for each backend, so its possible there is an error in only the sequential implementation.
This reveals that we need to add tests for using const iterators in scan.
Regarding the line of code mentioned in the error message, I'm not entirely sure what's going on because it does remove const (though not reference) so it should work to my eye. I'll try to dig into this later this week.

**Comment by rhornung67** [comment]
Thanks @MrBurmark I stared at it for a bit and didn't see anything that would make me think it wouldn't work.

**Comment by MrBurmark** [comment]
@mclarsen Can you try #1202 and see if that fixes your scan compile problems?
You may also want to use loop instead of sequential policies to allow the compiler to optimize more, in some cases.

**Comment by mclarsen** [comment]
I tried but its more difficult to test than I anticipated. When I point the build system at the commit, my raja patch fails. I looked at the branch #1202 , and everything looks good. Once it's merged, feel free to close the issue.
