### ISSUE TITLE
Develop wrappers for atomic operations

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#120]
Some app developers have requested wrappers for atomic operations (like we have defined for CUDA reductions) so that they can use these in kernels in a portable way. For example, what we have now is a limited set and only works with CUDA. If you try to switch the execution policy to run the same code with OpenMP, for example, it won't work.

**Comment by trws** [comment]
These are coming in with @ajkunen's #312.

**Comment by rhornung67** [comment]
@ajkunen is this issue resolved completely? If so, please close.

**Comment by rhornung67** [comment]
Completed in recent @ajkunen PR merge.
