### ISSUE TITLE
Add reset() method to SYCL reduction types

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1203]
These appear to be missing and are preventing us from enabling SYCL reduction tests in our CI.  For example,

https://github.com/LLNL/RAJA/blob/develop/test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMin.hpp#L63

@homerdin do you have time to add these?

**Comment by homerdin** [comment]
@rhornung67 Yeah I will get them added and push a branch.

**Comment by rhornung67** [comment]
Thank you. We appreciate it.

**Comment by rhornung67** [comment]
We will only support new reduction interface for SYCL
