### ISSUE TITLE
CMAKE_CUDA_ARCHITECTURES

### ISSUE THREAD

**Issue by adayton1** [LLNL/RAJA#1210]
It looks like RAJA is using custom variables for setting the CUDA architecture (CUDA_ARCH and CUDA_CODE, see https://github.com/LLNL/RAJA/blob/develop/CMakeLists.txt#L114). In CMake 3.18, a new variable called CMAKE_CUDA_ARCHITECTURES is provided so that CMAKE_CUDA_FLAGS does not have to be modified directly. 

https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_ARCHITECTURES.html

**Comment by MrBurmark** [comment]
It looks like this is going to be important with newer cmake versions, I tried using 3.21.1 with our scripts on rzansel and got a warning for every target that CUDA_ARCHITECTURES is empty.

**Comment by adayton1** [comment]
This was done in the latest release.
