### ISSUE TITLE
Enabling NESTED yields unexpected compiler warnings

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#125]
This report is based on the develop branch. I noticed that CMakeLists.txt has 
`option(RAJA_ENABLE_NESTED "Enable nested loop support" Off)`
Because I am using the nested capabilities, I thought I should build RAJA as follows:
cmake   -DCMAKE_C_COMPILER=`which gcc` -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`cd ../../external_install ; pwd` -DBUILD_SHARED_LIBS=On -DRAJA_ENABLE_CUDA=On -DRAJA_ENABLE_NESTED=On `cd .. ; pwd`

Enabling nested yields these compiler messages:
build-chaos-gnu-release/include/RAJA/config.hxx:86:0: warning: "RAJA_ENABLE_NESTED" redefined
 #define RAJA_ENABLE_NESTED
 ^

**Comment by davidbeckingsale** [comment]
Thanks for the report :) Enable nested gets forcibly defined so that the tests build, it can be ignored for now, and won't impact your application builds (these redefinitions are only passed on the command line when building the tests)
