### ISSUE TITLE
Tensor Range Inclusive Index?

### ISSUE THREAD

**Issue by rchen20** [LLNL/RAJA#1263]
@ajkunen Do we want the TensorIndex to be an inclusive range, i.e. `[begin, end]`?

https://github.com/LLNL/RAJA/blob/87a5cac67214e5e96c941bd652b1c0981e9f2123/include/RAJA/pattern/tensor/TensorIndex.hpp#L51

I suppose other ranges in RAJA have exclusive ends, but this was giving me an off-by-1 error. I could just add documentation to indicate this range is exclusive as well.

**Comment by artv3** [comment]
It would be nice to be consistent with the rest of RAJA

**Comment by rhornung67** [comment]
we recently changed the offset view to use exclusive range so it is consistent with the rest of RAJA

**Comment by rhornung67** [comment]
leave as is
