### ISSUE TITLE
Extend run-time policy section to forall

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#1264]
Various packages have been creating a layer over RAJA which instantiates both host and device policies. Based on a run-time compute-policy the correct forall method is then launched (see example below). 

It would clean up a lot of code in applications to support this capability directly in RAJA. Something we can use to support this feature is using a runtime resource by a given platform. 

```
template <typename KERNEL>
void launch(const int n, KERNEL && k)
{
   if (compute_policy == RAJA::Policy::cuda)
   {
#ifdef RAJA_ENABLE_CUDA
      RAJA::forall<RAJA::cuda_exec<256, true>>(RAJA::TypedRangeSegment<int>(0, n), k);
#else
      fprintf(stderr, "cuda not enabled");
      exit(1);
#endif
   }
   else if (compute_policy == RAJA::Policy::hip)
   {
#ifdef RAJA_ENABLE_HIP
      RAJA::forall<RAJA::hip_exec<256, true>>(RAJA::TypedRangeSegment<int>(0, n), k);
#else
      fprintf(stderr, "hip not enabled");
      exit(1);
#endif
   }
   else if (compute_policy == RAJA::Policy::sequential)
   {
      RAJA::forall<RAJA::loop_exec>(RAJA::TypedRangeSegment<int>(0, n), k);
   }
   else
   {
      fprintf(stderr, "unsupported exec policy");
      exit(1);
   }
}
```

**Comment by rhornung67** [comment]
To be more general, flexible, and clear, I suggest the following:

1. Change name of method to 'forall_launch' so it's clear what RAJA kernel execution method is being invoked under the covers.
2. Make method templated on segment type and replace first int arg with arg of segment type.
3. It would be nice to have flexibility for users to choose different threads/block for GPU execution, and also to choose whether to launch synchronously or asynchronously, etc.

Perhaps, thinking about a different design/implementation of this would help. Maybe have user create a "launch object" that could set launch options for different back-ends via ctro or set() methods?

**Comment by amklinv-nnl** [comment]
I would also appreciate this support being in raja natively. I'm generally a kokkos user and was surprised to see raja doesn't already support this.

**Comment by trws** [comment]
@amklinv-nnl, has something been added to Kokkos to support runtime policy selection? Last I knew it didn't provide such a feature either, but rather the set of `DefaultHost/DevicePolicy` types so that whatever was selected when Kokkos was built would be used.  That's something else I think we should have, truth be told, but it's a bit different than what we're discussing here.

**Comment by artv3** [comment]
resolved in https://github.com/LLNL/RAJA/pull/1280
