### ISSUE TITLE
Build fails when we have an installed RAJA and a RAJA in development

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/RAJA#129]
Hey all,

I had a RAJA install in my home directory from when I was playing with CUDA/Clang. I went to do some Caliper work, and built without CUDA

`cmake -DRAJA_ENABLE_CALIPER=ON -DCMAKE_CXX_COMPILER=`which g++`-DCMAKE_C_COMPILER=`which gcc`..`

And got errors related to cuda.h not being found. It turns out I had CMAKE_PREFIX_PATH set (a way of integrating CMake packages), which led to the installed RAJA config.hxx being found and CUDA being enabled. Users shouldn't encounter this bug, but we should look at protecting against it (I'm not sure the mechanism).

We should look at fixing this when we move to the broader build system repairs

**Comment by davidbeckingsale** [comment]
Thanks for opening this. Hopefully it may be resolved with our header file re-organization.

**Comment by davidbeckingsale** [comment]
Thinking about this further, I'm not sure whether it was a bug or not. Any other package would probably fail in weird ways if you were including header files from another version when you tried to build the current version. Thoughts?
