### ISSUE TITLE
Consider collapsing seq_exec and loop_exec at least for tests

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#1307]
For example, commenting out the 3 reorderings and switches of loop/seq in the SequentialKernelLocExecPols list in test-kernel-reduceloc.cpp.in reduces compile time for the Min2DView-Sequential object file from ~37 seconds to ~7 seconds on my workstation with clang.  I have a feeling we're getting bit by doing cartesian product testing over what are essentially equivalents like this in a number of places, and while it doesn't make much end to end difference to do one of these on a fast box, it should have a meaningful impact on CI and slower compilers to weed some of these out.

**Comment by artv3** [comment]
I was wondering, should we deprecate seq_exec? or remove loop_exec and just have seq_exec have loop_exec behavior?

**Comment by trws** [comment]
Personally I've never really seen a reason for seq_exec outside of the context of RajaPerf, it can serve as an explicitly deoptimized baseline, but why do we want that in RAJA's interface? I hope @rhornung67 will forgive me because I know we've discussed this before, but I honestly can't remember what the reasoning was anymore.

**Comment by rhornung67** [comment]
IIRC, early on we introduced seq_exec and loop_exec so we could compare performance between cases when we forced the compiler to turn off SIMD optimizations vs. when we let the compiler do its thing. I don't know how important this really is at this point. I'm open to any of your proposals. What do others think? @MrBurmark @artv3 @rchen20 @mdavis36 @davidbeckingsale

**Comment by rhornung67** [comment]
I don't believe we apply loop_exec or seq_exec consistently across the Perf Suite, FWIW. I should probably take a pass through and switch all seq_exec to loop_exec. That is the right comparison we want to have.

**Comment by trws** [comment]
If that's the case, we could nix seq_exec and make it an alias for loop_exec for a while as a deprecation period. That would even automatically cut down the build times since the types would be identical and the instantiations would get reused.

**Comment by rhornung67** [comment]
I forget. Do both seq_exec and loop_exec work inside CUDA kernels for all RAJA::kernel exec policies? I faintly recall this was an issue at some point.

**Comment by rhornung67** [comment]
> If that's the case, we could nix seq_exec and make it an alias for loop_exec for a while as a deprecation period. That would even automatically cut down the build times since the types would be identical and the instantiations would get reused.

Agreed. We also have simd_exec, which we haven't really determined whether that really does what we think it should.

**Comment by trws** [comment]
They should, if they don’t it would almost certainly be because of plugin system issues and we should propagate the fixes either way.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On August 5, 2022 at 12:55:46 PM PDT, Rich Hornung ***@***.***> wrote:

I forget. Do both seq_exec and loop_exec work inside CUDA kernels for all RAJA::kernel exec policies? I faintly recall this was an issue at some point.

**Comment by trws** [comment]
Good point about simd_exec, I'm honestly not sure about that one.  As it is it may or may not do a whole lot, but if we treat it as unsequenced or a safe_len of 1 then it would probably have pretty consistent effect.  Maybe worth testing to see if we want to keep it and if so in what form, especially since @ajkunen's explicit simd stuff has landed.

**Comment by rhornung67** [comment]
We only have seq_exec now. Other policies mentioned here are type aliases to that. We will remove all unused policy types for next release.
