### ISSUE TITLE
Add ability to turn off vectorization.

### ISSUE THREAD

**Issue by rchen20** [LLNL/RAJA#1327]
Something like `RAJA_ENABLE_VECTORIZATION` to CMake for turning this off for non-vector builds.

**Comment by gzagaris** [comment]
Note, along those lines, PR #1302 added a `RAJA_ENABLE_SIMD` CMake option

**Comment by rhornung67** [comment]
@rchen20 I spoke to Adam and he is OK with making this a compile-time option. Please put up a PR that adds the CMake variable RAJA_ENABLE_VECTORIZATION defaulted to Off and add the guard to the appropriate files 9headers, tests, etc.

**Comment by rchen20** [comment]
Addressed in #1339.
