### ISSUE TITLE
Wish there was a omp_collapse_exec policy

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#133]
I would like to be able to make a policy like this:
`typedef RAJA::NestedPolicy<RAJA::ExecList< RAJA::omp_collapse_exec, RAJA::omp_collapse_nowait_exec, RAJA::simd_exec > > fine;`
If the policy uses nowait, as in the following example, I need to have a barrier at the end to ensure that the main thread waits for all the threads to finish.

    typedef RAJA::NestedPolicy<RAJA::ExecList< RAJA::omp_collapse_nowait_exec, RAJA::omp_collapse_nowait_exec, RAJA::simd_exec > > finenowait;
    RAJA::forallN<finenowait>(iter1, iter2, inter3, [=] (Iter1 i1, Iter2 i2, Iter3 i3) { /* whatever */ });
    #pragma omp barrier

**Comment by ajkunen** [comment]
@tepperly, There are two ways this could work are you calling forallN inside of an existing OMP parallel region?

If you are already inside of a parallel region,  then I don't really have a solution for that right now... but you are probably breaking encapsulation somehow anyways (by using omp pragmas).

If you are not, then here is what you want:
```
typedef RAJA::NestedPolicy<RAJA::ExecList< RAJA::omp_collapse_nowait_exec, RAJA::omp_collapse_nowait_exec, RAJA::simd_exec >, OMP_Parallel> finenowait;
RAJA::forallN<finenowait>(iter1, iter2, inter3, [=] (Iter1 i1, Iter2 i2, Iter3 i3) { /* whatever */ });
#pragma omp barrier
```

This will wrap the entire forallN loop structure inside of an OMP parallel region, which upon exit will for synchronization. 

I suppose we could add an execution policy that performs an "omp barrier" upon exit, that would be useful, and would also solve this.

Let me know what your use case is, and we can figure something out for you.

**Comment by tepperly** [comment]
Could I have determined this solution from documentation somewhere?

In your "here is what you want", there is still a `#pragma omp barrier`. Was that unintentionally included there?  Your text suggests that it isn't needed with the OMP_Parallel.

**Comment by davidbeckingsale** [comment]
@tepperly I think the `#pragma omp barrier` in @ajkunen's response is unintentional. By creating an OpenMP parallel region, there is an implicit barrier at the end of the region.

Re determining this from the documentation,  I would say no. We already have an issue (#104) for improving the documentation for these forallN policies.

**Comment by tepperly** [comment]
Based on experimenting, it looks like there is another change to Adam's suggestion.

    typedef RAJA::NestedPolicy<RAJA::ExecList< RAJA::omp_collapse_nowait_exec, RAJA::omp_collapse_nowait_exec, RAJA::simd_exec >, RAJA::OMP_Parallel<> > finenowait;
    RAJA::forallN<finenowait>(iter1, iter2, inter3, [=] (Iter1 i1, Iter2 i2, Iter3 i3) { /* whatever */ });

Just to highlight, I am leaving out the `#pragma omp barrier`, and I am using `RAJA::OMP_Parallel<>` (adding the less than greater than).

**Comment by tepperly** [comment]
FYI, trying out the OMP_Parallel approach causes my tests to fail.

**Comment by tepperly** [comment]
Looks like it's my mistake.

**Comment by ajkunen** [comment]
Ok!  Glad it worked.

We will be working toward better documentation and either more documented examples or a tutorial.  It’s on my todo list.

-Adam
