### ISSUE TITLE
TODO: Spack packaging and RADIUSS CI

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/RAJA#1330]
Tasks remaining to achieve clean Spack/RADIUSS CI configuration:

- [x] Port RAJA spack package to CachedCMakePackage (simplified logic for host-config file generation).
- [x] Synchronize Local packages with upstream one (ideally, there should not be a need for local packages after a release).

**Comment by rhornung67** [comment]
Eliminating the local package would be good as it has been a point of confusion for users.

**Comment by adrienbernede** [comment]
And the risk is that the divergence with the upstream package is such that there could be issues building RAJA with Spack while we use it in CI... that would be a pity.

**Comment by rhornung67** [comment]
@adrienbernede is this done?

**Comment by adrienbernede** [comment]
Yes
