### ISSUE TITLE
WSC/CP apps production compilers.

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1378]
Collecting info here for consideration when updating Gitlab CI specs.

Toss 3 
- [ ] Intel 19.1.3 (not avail as module?)
- [ ] Intel 19.1.0
- [ ] Intel 19.1.2 (w/gcc 8.3.1 toolchain)
- [ ] gcc 10.2.1
- [ ] clang 14.0.4

Toss 4
- [ ] Intel 19.1.3 (not avail as module?)
- [ ] Intel 19.1.2
- [ ] Intel-tce/2022.1.0
- [ ] Intel-classic-tce/2021.6.0

Toss 4 Cray (EAS3)
- [ ] rocm-tce/5.2.3  (move to 5.3.0)

Blueos
- [ ] clang 12.0.1 + CUDA 10.1.243 (old, but system default)
- [ ] clang 14 + CUDA 11.7
- [ ] XL-2022.06.01 + CUDA 11.7
- [ ] XL-2020.08.24 + CUDA 11.0.2
- [ ] gcc-8.3.1 + CUDA 11.7

Trinity
- [ ] Intel 19.1.3

**Comment by artv3** [comment]
We currently use the following: 
Toss 4:  ROCM 5.4.3
Blueos:  xl-2022.08.19 + cuda-11.1.1
Toss 3:  clang 12.0.1, gcc 8.3.1 ,  intel 19.1.2

**Comment by adayton1** [comment]
We use the following:
Toss 4 Cray: ROCm 5.4.3
Toss 4: Intel Classic 19.1.2, Intel oneAPI 2022.1.0
Blueos: clang 14.0.5 + CUDA 11.7.0
Toss 3: Intel oneAPI 2022.2, clang 14.0.4, gcc 10.2.1

**Comment by rhornung67** [comment]
Closing. RADIUSS shared CI specs represent production code usage. Will review and update specs periodically.
