### ISSUE TITLE
RAJA 2022.10.3 patch list

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#1387]
- [x] Device macrofix https://github.com/LLNL/RAJA/pull/1386
- [x] #1388 
- [x] : the inclusion of bltTargets.cmake from raja-config.cmake should be done before the call to find_dependency(camp ...) - https://github.com/mfem/mfem/pull/3293#issuecomment-1321416716 -- resolved in https://github.com/LLNL/RAJA/pull/1389

**Comment by rhornung67** [comment]
@artv3 this is done and can be closed, right?

**Comment by artv3** [comment]
Yes
