### ISSUE TITLE
Easily confuseable RAJA_DEVICE_* macros

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#1395]
We have `RAJA_DEVICE_CODE` and `RAJA_DEVICE_ACTIVE` macros where RAJA_DEVICE refers to different things in each macro.

If `RAJA_DEVICE_CODE` is defined this is the device compile pass.
If `RAJA_DEVICE_ACTIVE` is defined then the cuda, hip, or sycl backend is enabled and active.

**Comment by MrBurmark** [comment]
I recommend `RAJA_DEVICE_CODE` becomes `RAJA_DEVICE_CODE_COMPILE_PASS`.

@artv3 suggested `RAJA_DEVICE_ACTIVE ` becomes `RAJA_DEVICE_IS_AVAILABLE` here https://github.com/LLNL/RAJA/pull/1393#discussion_r1037355557.

I suggest `RAJA_DEVICE_ACTIVE ` becomes `RAJA_GPU_BACKEND_ACTIVE `. I would like to keep the `ACTIVE` part because it is used in the cuda, hip, and sycl macros to indicate that the back-end is enabled and the file is being compiled with a compiler capable of compiling cuda, hip, or sycl.

**Comment by rhornung67** [comment]
I think making the macro names more clear and explicit is a good idea. However, I think the choice of DEVICE or GPU in the name should be consistent; i.e., use one or the other but not both.

**Comment by MrBurmark** [comment]
@rhornung67 To me it is the use of this same DEVICE term that is the root of the confusion.

**Comment by MrBurmark** [comment]
How about having `RAJA_GPU` be the generic root?
Then we could have `RAJA_GPU_DEVICE_COMPILE_PASS_ACTIVE` and `RAJA_GPU_ACTIVE`.

**Comment by artv3** [comment]
I like it!

**Comment by rhornung67** [comment]
Me too!

**Comment by rhornung67** [comment]
@MrBurmark @artv3 pulling on this thread further, should we also rename the function/lambda decoration macros RAJA_DEVICE, RAJA_HOST, and RAJA_HOST_DEVICE to something like RAJA_DEVICE_ATTR, RAJA_HOST_ATTR, RAJA_HOST_DEVICE_ATTR (where ATTR indicates 'attribute')? It's more verbose, but does this make the code clearer?

**Comment by rhornung67** [comment]
Done and merged
