### ISSUE TITLE
Unused expression warning

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#1418]
```
include/RAJA/pattern/params/forall.hpp:61:7: warning: expression result unused [-Wunused-value]
      CAMP_EXPAND(detail::resolve<EXEC_POL>( camp::get<Seq>(f_params.param_tup) ));
```

```
tpl/camp/include/camp/helpers.hpp:45:3: note: expanded from macro 'CAMP_EXPAND'
  ::camp::detail::__expand_array_type { 0, ((void)(__VA_ARGS__), 0)... }
```

Using hipcc-5.2.0

**Comment by MrBurmark** [comment]
I'm pretty sure that I fixed that in camp, is our camp version up to date?

**Comment by rhornung67** [comment]
@MrBurmark I think I forgot to do a PR to merge the v2022.10.4 release back into develop. Let me verify and put up a PR for that if needed.

**Comment by rhornung67** [comment]
@MrBurmark if your submodule PR fixes the warning, you can close this.

**Comment by artv3** [comment]
yes looks great! thanks!
