### ISSUE TITLE
Reminder to make loc reducer constructor and reset signatures consistent

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#1424]
This is a reminder to make the arguments to the loc reducers constructor and reset method consistent. #1415 
Currently the reset method defaults the initial location but the constructor does not. Change reset to match the constructor.

**Comment by rhornung67** [comment]
@MrBurmark does https://github.com/LLNL/RAJA/pull/1415 resolve this issue?

**Comment by MrBurmark** [comment]
No, the second argument to reset is still defaulted.

**Comment by rhornung67** [comment]
Got it. Thanks.
