### ISSUE TITLE
Invalid device function on first kernel

### ISSUE THREAD

**Issue by adayton1** [LLNL/RAJA#1430]
I updated to the latest CAMP, Umpire, RAJA, and CHAI (from 2022.03 to 2022.10) and now my tests are crashing on the first call to RAJA::forall<RAJA::cuda_exec<256, true>>:

```
C++ exception with description "CUDAassert: invalid device function <path>/<to>/<installed>/<RAJA>/include/RAJA/policy/cuda/MemUtils_CUDA.hpp:229" thrown in the test body.
```

Any ideas what might be causing this?

**Comment by adayton1** [comment]
I'm seeing this on rzansel.

**Comment by artv3** [comment]
can you post your test kernel?

**Comment by rhornung67** [comment]
Did the args passed to RAJA::launch change?

**Comment by artv3** [comment]
> Did the args passed to RAJA::launch change?

Yes there was an API change, but I think this is for forall right @adayton1 ?

**Comment by rhornung67** [comment]
Sorry, I was confused. I thought this line https://github.com/LLNL/RAJA/blob/develop/include/RAJA/policy/cuda/MemUtils_CUDA.hpp#L221 was related to RAJA::launch.

**Comment by rhornung67** [comment]
@adayton1 I think that CUDA error you are seeing may be related to which target architecture the code was compiled for. Due to the CMake version bump, we now use CMAKE_CUDA_ARCHITECTURES to pass the arch to the compiler. Also, instead of 'sm_70', for example, it is now just '70'.

**Comment by adayton1** [comment]
It looks like we're doing a mix of things. We do specify CMAKE_CUDA_ARCHITECTURES, but I think we also manually add -code sm_70 to BLT_CUDA_FLAGS.

**Comment by rhornung67** [comment]
Could the problem be related to that? I don't see anything in the new RAJA release that would cause kernels to fail like what you're seeing.

**Comment by adayton1** [comment]
It's possible. I'll play around with it a bit. However, it did look like the stack trace had something to do with RAJA::launch under the hood, so I wanted to see if there were any relevant changes there, too. Unless the stack trace has been corrupted by this point.

**Comment by rhornung67** [comment]
I mis-interpreted the line where the error occurs. It's unrelated to RAJA::launch. Sorry for the confusion.

**Comment by adayton1** [comment]
I get the same error in RAJA's test-forall-RangeSegment-Cuda.exe. Here's the compile line for that test:

cd /g/g17/dayton8/ale3d/update_raja_stack/imports/raja/build-blueos_sierra_clang-relwithdebinfo/test/functional/forall/segment && /usr/tce/packages/cuda/cuda-11.7.0/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-ibm-14.0.5/bin/mpiclang++ -DGTEST_HAS_DEATH_TEST=1 -DGTEST_HAS_PTHREAD=0 -I/g/g17/dayton8/ale3d/update_raja_stack/imports/raja/test/include -I/g/g17/dayton8/ale3d/update_raja_stack/imports/raja/test/functional/forall/segment/tests -I/g/g17/dayton8/ale3d/update_raja_stack/cmake/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest -I/g/g17/dayton8/ale3d/update_raja_stack/imports/raja/include -I/g/g17/dayton8/ale3d/update_raja_stack/imports/raja/build-blueos_sierra_clang-relwithdebinfo/include -isystem=/g/g17/dayton8/ale3d/update_raja_stack/cmake/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/include -isystem=/usr/tce/packages/cuda/cuda-11.7.0/include -isystem=/g/g17/dayton8/ale3d/update_raja_stack/lib/blueos_sierra_clang/camp/2022.10.1.a/compiler-clang-ibm-14.0.5-xl-2022.08.19/cpp-14/blt-0.5.2.a/cmake-3.23.1/cuda-11.7.0/include -lineinfo  -DCUB_REPORT_PTX_ARCH=700 -restrict --expt-extended-lambda --expt-relaxed-constexpr -Xcudafe "--display_error_number" -g -lineinfo -O2 --generate-code=arch=compute_70,code=[compute_70,sm_70] -Xcompiler=-fPIE -Xcompiler=-fopenmp=libomp -std=c++14 -MD -MT test/functional/forall/segment/CMakeFiles/test-forall-RangeSegment-Cuda.exe.dir/test-forall-RangeSegment-Cuda.cpp.o -MF CMakeFiles/test-forall-RangeSegment-Cuda.exe.dir/test-forall-RangeSegment-Cuda.cpp.o.d -x cu -rdc=true -c /g/g17/dayton8/ale3d/update_raja_stack/imports/raja/build-blueos_sierra_clang-relwithdebinfo/test/functional/forall/segment/test-forall-RangeSegment-Cuda.cpp -o CMakeFiles/test-forall-RangeSegment-Cuda.exe.dir/test-forall-RangeSegment-Cuda.cpp.o

**Comment by adayton1** [comment]
And the link line:

/usr/tce/packages/cuda/cuda-11.7.0/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-ibm-14.0.5/bin/mpiclang++  -lineinfo  -DCUB_REPORT_PTX_ARCH=700 -restrict --expt-extended-lambda --expt-relaxed-constexpr -Xcudafe "--display_error_number" -g -lineinfo -O2 --generate-code=arch=compute_70,code=[compute_70,sm_70] -Xcompiler=-L/usr/tce/packages/clang/clang-ibm-14.0.5/lib,-lomp,-lomptarget-nvptx,-lxlsmp,-L/usr/tce/packages/xl/xl-2022.08.19/alllibs,-lxlsmp,-lomptarget-nvptx -Xcompiler=-L/usr/tce/packages/cuda/cuda-11.7.0/lib64 -Xcompiler=-fPIC -Wno-deprecated-gpu-targets -shared -dlink "CMakeFiles/test-forall-RangeSegment-Cuda.exe.dir/test-forall-RangeSegment-Cuda.cpp.o" -o CMakeFiles/test-forall-RangeSegment-Cuda.exe.dir/cmake_device_link.o   -L/usr/tce/packages/cuda/cuda-11.7.0/nvidia/targets/ppc64le-linux/lib/stubs  -L/usr/tce/packages/cuda/cuda-11.7.0/nvidia/targets/ppc64le-linux/lib  ../../../../lib/libgtest_main.a ../../../../lib/libgtest.a ../../../../lib/libRAJA.a /g/g17/dayton8/ale3d/update_raja_stack/lib/blueos_sierra_clang/camp/2022.10.1.a/compiler-clang-ibm-14.0.5-xl-2022.08.19/cpp-14/blt-0.5.2.a/cmake-3.23.1/cuda-11.7.0/lib/libcamp.a /usr/tce/packages/cuda/cuda-11.7.0/lib64/libcudart_static.a  -ldl -lcudadevrt -lcudart_static -lrt

**Comment by adayton1** [comment]
Still fails with CUDA 11.2.0.

**Comment by rhornung67** [comment]
@adayton1 I just build RAJA v.2022.10.4 on rzansel with CUDA 11.2.0 and clang-ibm-14.0.5 and it works for me. Try running our build script in the top-level RAJA directory: ./scripts/lc-builds/blueos_nvcc_clang.sh 11.2.0 70 ibm-14.0.5 and then run make -j in the build directory that is created. Compare the compile and link lines with that and what you have to see what the differences are.

**Comment by adayton1** [comment]
It looks like two major differences in the compile lines:

--ccbin points to the MPI wrapper in our compile line
We have rdc turned on (does the workgroup functionality require this, or can we turn it off?)

**Comment by adayton1** [comment]
We do a separate device link step, then use the host linker, whereas it looks like RAJA does that all in one step.

**Comment by MrBurmark** [comment]
rdc should be enabled if you're using workgroup to fuse kernels.

**Comment by adayton1** [comment]
Rich, I added CMAKE_CUDA_SEPARABLE_COMPILATION=ON to the blueos_nvcc_clang.sh script and ran it as follows: `./scripts/lc-builds/blueos_nvcc_clang.sh 11.2.0 70 ibm-14.0.5`

With that configuration, test-forall-RangeSegement-Cuda.exe crashes with the same error.

**Comment by rhornung67** [comment]
@adayton1 this issue can be closed, correct?

**Comment by adayton1** [comment]
Yeah, this can be closed. Thanks!
