### ISSUE TITLE
Mysterious warning compiling RAJA + CUDA on Lassen

### ISSUE THREAD

**Issue by kab163** [LLNL/RAJA#1449]
On Lassen, do the following:
```
module load cuda/10.2.89
module load cmake/3.20.2 
module load gcc/8.3.1
```
And cmake command:
```
cmake -DENABLE_CUDA=On -DENABLE_OPENMP=Off -DCMAKE_CUDA_ARCHITECTURES=70 -DCMAKE_CUDA_COMPILER=/usr/tce/packages/cuda/cuda-10.2.89/bin/nvcc -DCUDA_TOOLKIT_ROOT_DIR=/usr/tce/packages/cuda/cuda-10.2.89 -DBLT_CXX_STD=c++14 -DCMAKE_BUILD_TYPE=Release -DRAJA_ENABLE_EXERCISES=On ../
```
During compilation, I see this warning:
```
/g/g0/belcher6/RAJA/include/RAJA/util/zip.hpp(72): warning #2976-D: calling a __host__ function("std::__copy_move<(bool)1, (bool)0,     ::std::random_access_iterator_tag> ::__copy_m< ::RAJA::ZipIterator<int *, unsigned int * > ,  ::RAJA::zip_tuple<(bool)1, int, unsigned int >  *> ") from a __host__ __device__ function("std::move< ::RAJA::ZipIterator<int *, unsigned int * > ,  ::RAJA::zip_tuple<(bool)1, int, unsigned int >  *> ") is not allowed
```
My changes that I'm building/testing for do not touch that .hpp file, and my codes runs just fine. I imagine though this could be a potential problem at some point down the line.

**Comment by MrBurmark** [comment]
I have seen these warnings as well. I'm pretty sure the compiler shouldn't be complaining as std::move is allowed in device code. I have been ignoring them and hoping things turn out ok, the device sort test pass and they do use this code on the device.

**Comment by MrBurmark** [comment]
Maybe we could work around these warnings by making our own version of move or using a static cast instead.

**Comment by rhornung67** [comment]
warnings like this tend to be somewhat inconsistent across compilers and versions. The warning doesn't show up when using nvcc 11.2.0 for example (same gcc 8.3.1).  IMO, nvcc is complaining about something that it should not.

**Comment by kab163** [comment]
> warnings like this tend to be somewhat inconsistent across compilers and versions. The warning doesn't show up when using nvcc 11.2.0 for example (same gcc 8.3.1). IMO, nvcc 10.2.89 is complaining about something that it should not.

Let me try cuda 11. If I can reproduce that (having the warning go away) then I think it would be reasonable to assume it's a non-issue. Thanks, Rich and Jason!

**Comment by kab163** [comment]
Ok, that warning disappeared when using cuda/11.2.0.

Do we care about the `ptxas` warnings?
```
ptxas warning : Stack size for entry function '_Z18forone_cuda_globalIZN14IntroSortPairsI11forone_cuda11RunOnDeviceEclIN4RAJA4SpanIPdlEENS6_IPllEENS5_9operators4lessIddEEEEvOT_OT0_T1_EUlvE_EvT_' cannot be statically determined
```
But ya, we can close this issue then. Thanks again!

**Comment by rhornung67** [comment]
The stack size warnings are common and can probably be ignored if the code runs correctly. For example: https://github.com/kokkos/kokkos/issues/2039
