### ISSUE TITLE
Underwhelming performance of `dot` product using `RAJA::ReduceSum`.

### ISSUE THREAD

**Issue by YohannDudouit** [LLNL/RAJA#1465]
Hi,

I implemented a naïve `dot` product using `RAJA::ReduceSum`:
```c++
template < typename Vector >
real64 dot( const Vector & x, const Vector & y )
{
  RAJA::ReduceSum< parallelDeviceReduce, real64 > vsum(0.0);
  arrayView1d< real64 const > const localX = x.values();
  arrayView1d< real64 const > const localY = y.values();

  using POLICY = parallelDeviceAsyncPolicy<>;
  forAll< POLICY >(
     localX.size(),
     [vsum, localX, localY] GEOSX_HOST_DEVICE ( localIndex const i )
     {
       vsum += localX[ i ] * localY[ i ];
     }
  );
  return static_cast<real64>(vsum.get());
}
```

Unfortunately, the GPU (MI250X) performance of this function is very underwhelming.
<img width="732" alt="Screen Shot 2023-03-27 at 11 44 58 AM" src="https://user-images.githubusercontent.com/190171/228037362-792a6973-684c-486e-b40a-0fcf77d839f3.png">
Compared to rocm reduce:
<img width="732" alt="Screen Shot 2023-03-27 at 11 45 33 AM" src="https://user-images.githubusercontent.com/190171/228037172-b3173809-87e8-4faf-aaf7-7f8e5b8496cd.png">

Is there an easy solution to have a RAJA dot product that matches the performance of the rocm reduce?
Thank you in advance for your help!

**Comment by MrBurmark** [comment]
This is a known performance problem with reducers on MI250X beyond a problem size of about 250K. On the other hand below 250K the RAJA reducers generally do perform better than rocprim(and cub) as they launch fewer kernels.
What's happening is that beyond a certain point the way that Raja reducers sum up partial results starts to serialize. I am working on a fix for this, but it isn't in yet.
One thing you can try now is using atomics for summing partial results by using `hip_reduce_atomic` instead of `hip_reduce`.

**Comment by YohannDudouit** [comment]
Thank you very much @MrBurmark ! I tried it, it's still quite slower than rocm reduce, but not orders of magnitude slower.

**Comment by MrBurmark** [comment]
What problem sizes are you running?

**Comment by YohannDudouit** [comment]
It's not clear, I'm benchmarking from ~1K to ~80M dofs, but my intuition is that the 100K - 10M range is probably what users are going to use the most. The performance is much better at lower dofs with `RAJA::hip_reduce_atomic`! The discrepancy appears above 5M dofs. I actually think that with `RAJA::hip_reduce_atomic` the overall performance on the range of interest is better, the peak performance is a bit lower but that's okay as I don't see users using as much very high dofs counts.
