### ISSUE TITLE
Switch to one "seq" exec policy

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1468]
We currently have "seq_exec" and "loop_exec" policies that can be used with RAJA::forall and RAJA::kernel. The difference is that seq_exec applies #pragma novector to prevent any SIMD compiler optimization, while loop_exec lets the compiler do whatever it wants. We should remove one of these (deprecate at next release, and remove in the subsequent release).

We also have seq_reduce and seq_atomic policies that can be used with either of the exec policies. Not sure loop_reduce and
loop_atomic make sense? We should pick something consistent. How about remove loop_exec and keep seq_exec and remove no vector pragma. That would minimize the change for users since all they would have to do is switch loop_exec to seq_exec to get the same behavior.

**Comment by trws** [comment]
My preference would be to, at least at first, make `seq` and `loop` the same, and match what `loop` currently is.  As far as I know, the `seq` policy was really there for performance testing right?  Do you think we should have a way to get it for use in places like the perf suite or should we ditch it altogether?

**Comment by davidbeckingsale** [comment]
Maybe we could have a bool template param which defaults to allowing vectorization, and then using `RAJA::seq_exec<false>` would have the `#pragma novector`.
