### ISSUE TITLE
Find cause of excessive linker warnings on Tioga

### ISSUE THREAD

**Issue by rchen20** [LLNL/RAJA#1475]
The Tioga CI passes, but the pipeline does not finish due to exceeding the log limit with linker warnings, e.g. https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/1166724. What occurs is that the ROCM/5.1.1 tests build, run, and pass with the linker warning spew. In the subsequent ROCM/5.2.3 build, the linker spew exceeds the log limit.

The linker warnings start here during the ROCM/5.2.3 build and repeat:

```
[  2%] Linking CXX executable ../bin/resource-launch
[  2%] Linking CXX executable ../bin/resource-kernel
[  2%] Linking CXX executable ../bin/atomic-histogram
readelf: Warning: Unrecognized form: 0x23
readelf: Warning: Unrecognized form: 0x22
```

Note that this pipeline is using `-- Check for working CXX compiler: /opt/rocm-5.2.3/hip/bin/hipcc - skipped`. May need to try `/opt/rocm-5.2.3/llvm/bin/amdclang++`, or `/opt/rocm-5.2.3/llvm/bin/clang++` if available.

**Comment by rhornung67** [comment]
Something is wrong. The checks should not pass if the build doesn't complete and it's not marked allowed to fail. We need to talk to Adrien about this.

**Comment by rchen20** [comment]
Updated the description upon searching the log some more: The pipeline seems to begin linking all or nearly all files, but I cannot tell from the log whether linking finished. Still don't see any of the tests running.

**Comment by rhornung67** [comment]
@rchen20 is this still an issue (we are testing ROCm 5.6.0)? If not, please close.

**Comment by rhornung67** [comment]
@rchen20 is this still a problem for you? 

I just built RAJA with rocm 5.6.1 and there were only a few warnings related to inability to vectorize or unroll a loop.

If it's not an issue any longer, please close it.

**Comment by rchen20** [comment]
Looks like our CI has moved to ROCM/5.6.0, which I just tested and no longer generates these readelf warnings. Closing this issue.
