### ISSUE TITLE
Forall sycl reduction random fails

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#1494]
I've noted that SYCL reductions will randomly fail within a forall test. Waiting to hear back if we have a fix or if we should disable the sycl reduction test.

**Comment by MrBurmark** [comment]
Maybe just broken with old reduction interface?

**Comment by homerdin** [comment]
Yes, this is only broken with the old reduction interface.  #1541 removes support for minloc/maxloc with the old reduction interface for the SYCL backend.

**Comment by artv3** [comment]
Old reducers are not expected to work with sycl.
