### ISSUE TITLE
Does raja support SYCL？

### ISSUE THREAD

**Issue by wangzy0327** [LLNL/RAJA#1521]
how to verify SYCL？

**Comment by artv3** [comment]
There is some support with RAJA forall and launch API's. I believe reductions are not fully supported yet. 
Please see the following examples: 

https://github.com/LLNL/RAJA/blob/develop/exercises/vector-addition.cpp
https://github.com/LLNL/RAJA/blob/develop/examples/dynamic_mat_transpose.cpp

**Comment by rhornung67** [comment]
Actually, all RAJA::forall and most RAJA::kernel and RAJA::launch features are supported in the develop branch. SYCL reduction support is being developed in https://github.com/LLNL/RAJA/tree/feature/homerdin/sycl_reduction. Parallel scans and sorts are not available yet.  Available execution policies, etc. for SYCL are described in the RAJA User Guide.

**Comment by wangzy0327** [comment]
> There is some support with RAJA forall and launch API's. I believe reductions are not fully supported yet. Please see the following examples:
> 
> https://github.com/LLNL/RAJA/blob/develop/exercises/vector-addition.cpp https://github.com/LLNL/RAJA/blob/develop/examples/dynamic_mat_transpose.cpp

I  am not familiar with raja. What is the meaning of reductions?

**Comment by rhornung67** [comment]
@wangzy0327 can we close this issue.
