### ISSUE TITLE
Cuda Error with 0 length loop

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#160]
RAJA currently fails with the error message below if a cuda forall has 0 length.

CUDAassert: invalid configuration argument

**Comment by DavidPoliakoff** [comment]
We're launching a zero block kernel, aren't we?

**Comment by davidbeckingsale** [comment]
😞

**Comment by MrBurmark** [comment]
We attempt to launch a zero block kernel, but cuda doesn't like it.

**Comment by DavidPoliakoff** [comment]
CUDA is so whiny sometimes. We support 1 thread, >1 thread, why not 0 (or negative thread). Resolving WONTFIX, filing bug against NVIDIA

**Comment by davidbeckingsale** [comment]
We should probably add a similar unit-test for the CPU versions, and discuss whether it's worth issuing a warning in RangeSegment contstruction

**Comment by rhornung67** [comment]
Agree 100%.

**Comment by ajkunen** [comment]
Depending on how you have architected your algorithm, executing a zero-sized range segment may make sense, and it should do the right thing (NOP) without warning or error.

I also think that having a RangeSegment which begins after it ends (essentially a negative range) should be a NOP… any thought?


-Adam

**Comment by davidbeckingsale** [comment]
Both being NOP makes sense. It would be nice to catch some of these problems though, but I don't know the best way to handle it in the general case.

**Comment by rhornung67** [comment]
I think a NO-OP for these cases is preferable to a code halt. Should we add a macro (or other mechanism) to the code to emit warning messages consistently in debug code?

**Comment by ajkunen** [comment]
You could make an optional checking pound-def to enable that kind of warning... but in general it shouldn't start spewing warning messages for that when building debug

**Comment by davidbeckingsale** [comment]
Fixed by #162
