### ISSUE TITLE
Compilation issue with new clang/Intel

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1656]
Issue reported by @homerdin

Intel ran into this issue in their nightly testing with the newest clang compiler.  They created a smaller reproducer shown below (also [https://godbolt.org/z/7evq6GT5v](https://urldefense.us/v3/__https:/godbolt.org/z/7evq6GT5v__;!!G_uCfscf7eWS!YkUMYfh3QVaA_l_VgXndZ3hJ1GOiflwcSmbHlP9BoujrVo0z3N-03vrSXOndtDxkp-r79g046uey9r-sYAmurw$) ).  This is from [https://github.com/LLNL/RAJA/blob/eaa93614a319b26aef63b1236e505f93a37c463a/include/RAJA/pattern/kernel/Tile.hpp#L106](https://urldefense.us/v3/__https:/github.com/LLNL/RAJA/blob/eaa93614a319b26aef63b1236e505f93a37c463a/include/RAJA/pattern/kernel/Tile.hpp*L106__;Iw!!G2kpM7uM-TzIFchu!wqTqsmhFfVZq8ATNBFbq3G6KOVFIZUFYJ_BBFZWFCs9zodnRgua3BgAFzQ0eyHjv2X1gNVOMjR5l0O7_TXS8xuA$).
 
It looks like a bug that wasn’t being caught with older versions, but I’m not an expert on nested class member access.
 
Thanks,
Brian
 
#include <cstddef>
 
#define RAJA_INLINE inline  __attribute__((always_inline))
 
template <typename Iterable>
struct IterableTiler {
  using Index_type = std::ptrdiff_t;
 
  class iterator
  {
    const Index_type block_id;
 
  public:
    RAJA_INLINE bool operator!=(const IterableTiler &rhs) const
    {
      return block_id != rhs.block_id;
    }
 
    RAJA_INLINE bool operator<(const IterableTiler &rhs) const
    {
      return block_id < rhs.block_id;
    }
  };
 
};
 
bwhitney@exaperf-sdpcloud-pvc19:~/jira/cmplrllvm-58711> g++ -c x.cpp
bwhitney@exaperf-sdpcloud-pvc19:~/jira/cmplrllvm-58711> icpx -c x.cpp
x.cpp:16:30: error: no member named 'block_id' in 'IterableTiler<Iterable>'
   16 |       return block_id != rhs.block_id;
      |                          ~~~ ^
x.cpp:21:29: error: no member named 'block_id' in 'IterableTiler<Iterable>'
   21 |       return block_id < rhs.block_id;
      |                         ~~~ ^
2 errors generated.

**Comment by rhornung67** [comment]
@homerdin I don't know which specific compiler and version that produced the error. If you have access to it, will you please try to build the code in the branch associated with this PR: https://github.com/LLNL/RAJA/pull/1668 or have someone at Intel(?) try that branch.  The change I made resolves the issue in the Compiler Explorer example for every compiler I tried there.  

Please let me know the build/test results, if you have questions, or if there are other issues.  Thank you.

**Comment by homerdin** [comment]
@rhornung67 These changes have been tested with the Intel nightly compiler and everything is working.  Thanks!

**Comment by rhornung67** [comment]
Thanks @homerdin
