### ISSUE TITLE
Remove SYCL set/getQueue methods, part 2

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#1658]
The RAJA `setQueue` and `getQueue` methods are a remnant from before we were able to pass a resource to RAJA kernel execution methods. The remaining calls involve contents of the following files. Fully resolving the dependences on the getQueue methods may require some adjustment to code that is generic w.r.t. execution back-end. This may require some coordination with other back-end support.

- [ ] policy/sycl/MemUtils_SYCL.hpp
- [ ] policy/sycl/reduce.hpp

**Comment by rhornung67** [comment]
@johnbowen42 should we close this for now and then re-open if a future issue arises?

**Comment by johnbowen42** [comment]
Yeah I think so.  I couldn't find or reproduce any bugs related to this
