### ISSUE TITLE
OpenMP Target CI Checks

### ISSUE THREAD

**Issue by long58** [LLNL/RAJA#1671]
- [ ] Add OpenMP target offload CI checks on lassen (clang and xl)

There are various issues with clang and xl and OpenMP Targert such that I was unable to find a combination that would work when I tried it. clang.16.0.6.ibm.gcc.8.3.1 seemed to be the only compiler that I could use to even compile with OMPTarget, but it still had issues compiling several tests (leading me to have to disable them), and led to seg faults and random failures with other tests. So I'm not really sure the appropriate compiler or settings to use here.   

Migrated from #1611

**Comment by rhornung67** [comment]
Added in https://github.com/LLNL/RAJA/pull/1762
