### ISSUE TITLE
Inconsistency in reductions: Min/Max vs. MinLoc/MaxLoc

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/RAJA#171]
I noticed that we use `>` or `<` in ReduceMin and ReduceMax, but `<=` and `>=` in the Loc version. Is this intentional, and is this sensible?

**Comment by rhornung67** [comment]
Good catch.  I think we should be using < and > in all cases. To me, it makes most sense for the Loc versions to report the earliest min/max location over the set of indices.

**Comment by rhornung67** [comment]
Although it's arbitrary, I know that it's implemented that way in at least two app codes here.

**Comment by keasler** [comment]
I only log in about once a week.  I'm not quite sure that the decision is arbitrary, especially if you want reproducible output.  Let me look at the current implementation of these operators and get back to you be Wednesday afternoon.

**Comment by rhornung67** [comment]
I recommend that we follow the lead of current apps and use < and >.

**Comment by davidbeckingsale** [comment]
Fixed by #173
