### ISSUE TITLE
Loading old cmake versions on build scripts

### ISSUE THREAD

**Issue by chapman39** [LLNL/RAJA#1714]
I am new to RAJA and am trying to create an build on lassen. In the root CMakeLists.txt, the cmake version minimum is currently 3.23, but many of the scripts in `scripts/lc-builds/` contain a module load command of an older cmake version. For example: https://github.com/LLNL/RAJA/blob/develop/scripts/lc-builds/blueos_clang.sh#L33

Reproducing the issue:

```bash
ssh lassen
cd <RAJA_REPO>
./scripts/lc-builds/blueos_nvcc_clang.sh 10.2.89 70 10.0.1
```

**Comment by rhornung67** [comment]
Hi Alex,,

The bump to CMake 3.23 is recent and we clearly didn’t do an adequate job updating the scripts. I will do this before I leave today and put up a PR.  Thank you for pointing this out.

--Rich

From: Alex Tyler Chapman ***@***.***>
Date: Monday, August 12, 2024 at 2:07 PM
To: LLNL/RAJA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LLNL/RAJA] Loading old cmake versions on build scripts (Issue #1714)

I am new to RAJA and am trying to create an build on lassen. In the root CMakeLists.txt, the cmake version minimum is currently 3.23, but many of the scripts in scripts/lc-builds/ contain a module load command of an older cmake version. For example: https://github.com/LLNL/RAJA/blob/develop/scripts/lc-builds/blueos_clang.sh#L33<https://urldefense.us/v3/__https:/github.com/LLNL/RAJA/blob/develop/scripts/lc-builds/blueos_clang.sh*L33__;Iw!!G2kpM7uM-TzIFchu!2m17dSV25AshRoS7gKL7keHzz08zeYunN183xMP0a8MIGPjG1-pdSY-GLQCWcW4h9_EyITQc57Budt9l3F2Xm0MnOw$>

Reproducing the issue:

ssh lassen

cd <RAJA_REPO>

./scripts/lc-builds/blueos_nvcc_clang.sh 10.2.89 70 10.0.1

**Comment by rhornung67** [comment]
Resolved with PR merge
