### ISSUE TITLE
ltimes kernel underbenchmarks it out of date

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#1737]
**Describe the bug**

ltimes kernel under benchmarks it out of date. Some of the features it uses may not be supported or have moved namespace. 

**To Reproduce**

Build ltimes which is found in the benchmark.

**Expected behavior**

It should build.

**Comment by rhornung67** [comment]
Since there are two versions of LTIMES in RAJAPerf that are implemented using all RAJA variants, we could delete it in RAJA benchmarks.

**Comment by artv3** [comment]
The neat feature of the version in the benchmark folder is that it has a number of variations, launch, kernel, shared memory and usage of the vectorization framework. I was going take a few mins today to see if I can bring it up to date. If there are things missing I can reach out so we can further discuss.

**Comment by artv3** [comment]
I was able to address some of the issues in this PR: https://github.com/LLNL/RAJA/pull/1738. 

However; other areas involve the vectorization capabilities. I discussed with @rchen20 and he offered to take a look.
