### ISSUE TITLE
Fixing some issues that show up when -pedantic/-Werror=overflow used with GCC

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#181]
My development teams likes to compile with -pedantic, and there are some RAJA header files that are tripping up our build:

    $ diff -c ../../../RAJA/include/RAJA/operators.hxx operators.hxx
    *** ../../../RAJA/include/RAJA/operators.hxx    2016-12-21 13:34:16.441072744 -0800
    --- operators.hxx       2017-01-31 13:32:21.040317387 -0800
    ***************
    *** 245,251 ****
      RAJA_HOST_DEVICE constexpr T min()
      {
        return 0;
    ! };
      template <>
      RAJA_HOST_DEVICE constexpr int16_t min<int16_t>()
      {
    --- 245,252 ----
      RAJA_HOST_DEVICE constexpr T min()
      {
        return 0;
    ! }
    ! 
      template <>
      RAJA_HOST_DEVICE constexpr int16_t min<int16_t>()
      {
    ***************
    *** 296,302 ****
      RAJA_HOST_DEVICE constexpr T max()
      {
        return 0;
    ! };
      template <>
      RAJA_HOST_DEVICE constexpr int16_t max<int16_t>()
      {
    --- 297,303 ----
      RAJA_HOST_DEVICE constexpr T max()
      {
        return 0;
    ! }
      template <>
      RAJA_HOST_DEVICE constexpr int16_t max<int16_t>()
      {

The compiler also complains about the use of 0xFFFFF in RAJA/operators.xxx in the int16_t specialization of min<int16_t>() because we have -Werror=overflow.  To resolve this, I changed it to return -32768;

**Comment by davidbeckingsale** [comment]
Hey @tepperly - I think this was fixed by #182 - can you re-open if not?
