### ISSUE TITLE
Windows build does not install RAJA.dll file in CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#186]
Doing a cmake --target INSTALL for RAJA does not install the .dll file in the prefix directory.
This [article](http://stackoverflow.com/questions/21592361/cmake-install-not-installing-libraries-on-windows) seems to be the issue.

**Comment by DavidPoliakoff** [comment]
Excellent catch @tepperly , I'll take a look at it.

**Comment by tepperly** [comment]
Expect a pull request from me.

**Comment by DavidPoliakoff** [comment]
Even better!

**Comment by davidbeckingsale** [comment]
Fixed by #187
