### ISSUE TITLE
Compiling for shared libraries

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#19]
The rest of my code is compiled with -fPIC -DPIC, and RAJA won't compile out of the box with -fPIC -DPIC. I wish there was a way to do something like --enable-shared when configuring RAJA.  Simillarly, it would be nice if I could just --enable-cuda or --disable-cuda instead of having to reach in and pick a config file.

Regards,

Tom

**Comment by DavidPoliakoff** [comment]
Hey Tom,

Thanks for the feedback on this. Right now we have a very CMake-looking build system. Would you be uncomfortable with a build script that looked like

```
cmake -DBUILD_SHARED_LIBS=on -DRAJA_{ENABLE|DISABLE}_CUDA
```
?

I'm trying to split the difference between traditional CMake idioms and this feature, if something looking like that is acceptable we can talk about it with @rhornung67 , @keasler and @davidbeckingsale .

**Comment by davidbeckingsale** [comment]
The build system is designed to mirror that of the toolkit, but we could move towards a more idiomatic CMake style system. We could move towards supporting something like @DavidPoliakoff suggests, although I think the following would be better:

`cmake -DRAJA_USE_SHARED=On -DRAJA_USE_CUDA=On`

**Comment by tgamblin** [comment]
@davidbeckingsale's is configurable in `ccmake` like you would expect, too.

**Comment by DavidPoliakoff** [comment]
Excuse terseness, on phone.

Should at least support both on shared library side, -DBUILD_SHARED_LIBS is idiomatic CMake

**Comment by tgamblin** [comment]
@DavidPoliakoff is right.  I missed the `RAJA_USE_SHARED`.  `BUILD_SHARED_LIBS` is the standard `CMake` arg.  `-DRAJA_{ENABLE|DISABLE}_CUDA` is not -- you want an option that is either on or off to be editable in `ccmake`.

**Comment by davidbeckingsale** [comment]
I didn't realize the `-DBUILD_SHARED_LIBS` was standard CMake, so yup we should definitely support that.

**Comment by DavidPoliakoff** [comment]
Come to think of it, disable cuda is meaningless, but yeah, agreed with @tgamblin

**Comment by tgamblin** [comment]
All I'm really arguing for is to add options with, well, [`option()`](https://cmake.org/cmake/help/v3.0/command/option.html)

**Comment by davidbeckingsale** [comment]
This should be fixed by #20

**Comment by tepperly** [comment]
I think something like
`cmake -BUILD_SHARED_LIBS=On -DRAJA_USE_CUDA=On`
would be great. I am mainly trying to avoid having to patch RAJA or its build system for my application.

Thanks!

**Comment by davidbeckingsale** [comment]
If you are using CMake directly, the option `-DBUILD_SHARED_LIBS=On` will now use the -fPIC flag and build shared libraries. If you are using the script, add the option `-co BUILD_SHARED_LIBS=On` to get the same effect. These changes have been merged to develop.

**Comment by tepperly** [comment]
What's the policies for the different branches in RAJA?  I assume that customers such as myself are normally expected to pick up things when they migrate to the master branch?

**Comment by davidbeckingsale** [comment]
Master is for releases only. The default branch shown on GitHub is 'develop'.
We are sort of following  of the 'git-flow' model (http://nvie.com/posts/a-successful-git-branching-model/ <http://nvie.com/posts/a-successful-git-branching-model/>)

I would recommend working from develop.

**Comment by DavidPoliakoff** [comment]
Hey @tepperly : @davidbeckingsale is right on this, but there are a few models you can use (I've seen developments using Trilinos follow these)

1) Always on develop. Just pull down from develop as stuff comes in, always be up to date
2) Pull down releases. If you have an issue with the release (as in this case), you file an issue, wait for a bugfix, and pull down develop after the bugfix. Then you pull down the next release when it comes out, and stay there unless you have a reason not to.

There's a few others that I wouldn't recommend, but those are the two main ways people tend to interact with these products that are developed this way. Without stepping on @keasler and @rhornung67 's toes, there's often a preference on teams like RAJA to see people always up with develop as it means we get testers (and we really love testers!), but either workflow is common.

**Comment by rhornung67** [comment]
David P, nice summary.  I agree that most folks should be watching and pulling develop since there is a lot of churn right now as we are trying to improve things and add features.
