### ISSUE TITLE
Cilk reductions are broken.

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#204]
This appears to be related to how we use the shared reduction memory block (The cilk reductions are the only ones that use the shared memory block) and the return value of getMaxReduceThreadsCPU() is computed which is used in getCPUReductionMemBlock(). After looking at this for a bit, my head started to hurt. Fixing it is a low priority so just noting it in an issue for now.

**Comment by trws** [comment]
Cilk has been removed in #266.
