### ISSUE TITLE
Compile error with certain versions of gcc.

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#215]
```
include/RAJA/exec-cuda/MemUtils_CUDA.hxx:120:43: error: requested alignment is not an integer constant
 struct RAJA_ALIGNED_ATTR(DATA_ALIGN) CudaReductionDummyBlockType {
```
It looks like certain versions of GCC (4.8.5) have an issue with certain attribute arguments.
http://stackoverflow.com/questions/36642315/error-requested-alignment-is-not-an-integer-constant

**Comment by davidbeckingsale** [comment]
Don't use 4.8.5 😄
