### ISSUE TITLE
Establish file naming convention for files.

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#220]
We have a mixture of upper/lower case, underscores, use of "raja", etc. Let's follow a common naming scheme.  This should be captured in the coding guidelines.

**Comment by davidbeckingsale** [comment]
Let's use CamelCase as much as possible. Any objections?

**Comment by trws** [comment]
We currently have a mix of camel-case, uppercase, mixed upper and camel case, and lower-snake case.  Personally, I tend to agree with the google style guide and the boost style guide that lowercase and/or lower-snake case are preferable.

On this topic, why do we use .hxx for headers? I realize gcc recognizes .cxx as c++ files, but quite a few tools don't recognize .hxx, rather taking just .h or .hpp.

**Comment by davidbeckingsale** [comment]
`.hpp` would be good with me for headers. I think that with files containing classes, CamelCase makes sense. For other headers, lower case makes sense but it leaves us with this weird mixture, especially when users are selecting a subset of features with the new header re-org...

**Comment by ajkunen** [comment]
are we going to support Unicode filename?

**Comment by davidbeckingsale** [comment]
I hope so, I would also like to use emojis 🖕

**Comment by trws** [comment]
That's actually part of the aforementioned conventions, CamelCase is a type, lower_snake_case is a header or a variable.  It does kinda make sense to name the file after the type if that's all that's in it, but I generally like all lowercase for all files on the filesystem, mainly to not have to remember case in case-sensitive OSes honestly.

As to unicode, why not? That way we can put our regex-based html parser in [`h͔̗̐̅̄͘͡ę̟̠͓̟̠͋̆̏͑_̴̩̤̺͍̳̙̫̉ͨͪ͋ͧ̄̌̽ͬ͘c̡̳͖̲̟̰̼̙̳͔̍̅̀̏ͣ́͟o̮̥͈̟̰͖̎̽͑̍̍̎͑̐̀͠m̸̡̦̩̫͌ͥͦͩ̅̉͑ȩ̛̜͙̤̜̘̠̥̱͙̉̈̽͆̂͆̔ͦ̕s̨͙͉͖͎̳̀́ͣ̑ͧ̂̏ͯ́.̧̞͓̩̎͊̑ͮ̎̒̆̃ͅͅh̵͚̙̪̪͉̰̰͕͔̅ͤͮͥx̷̷̘̼̬̝̎ͪ̈́̄ͧ͌ͯ͛ͣx͔̤͙͓̝ͦ͋ͩ̈͗́́ͨ̀`](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags).

**Comment by ajkunen** [comment]
@trws forget that I ever mentioned it :)

**Comment by davidbeckingsale** [comment]
We have some kind of convention, adopted in #221 : 

- `CamelCase` for classes
- `snake_case` for everything else
- `hpp` for header extensions

I'm marking this closed for now.
