### ISSUE TITLE
OMP scans incorrect when N < P

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#229]
OMP scans are incorrect when the length of the input is smaller than the number of threads.

See scanopenmp.hxx:134-135.
134  `exclusive_inplace(seq_exec{}, begin + i0, begin + i1, f, init);`
135  `sums[pid] = *(begin + i1 - 1);`

**Comment by willkill07** [comment]
What do you want it to do? Should we really be computing the scan with OpenMP at this point or fall back to sequential?

**Comment by MrBurmark** [comment]
I think sequential makes more sense.

**Comment by DavidPoliakoff** [comment]
@davidbeckingsale : for the second header re-org where policy and pattern are decoupled, things like this may create a corner case where the application doesn't include sequential but this file needs it. Probably not a thing, but worth having in mind.

**Comment by davidbeckingsale** [comment]
Then we would have to include it here. Fixing up all the includes means we can just include what we use in any other header.

**Comment by DavidPoliakoff** [comment]
Cool, it's worth keeping this in mind, but especially in the case of sequential it shouldn't matter then.

**Comment by davidbeckingsale** [comment]
Closed by #236
