### ISSUE TITLE
./scripts/config-build.py AssertionError: Could not find cmake cache file

### ISSUE THREAD

**Issue by chunhualiao** [LLNL/RAJA#23]
Hi, I was following instructions on http://software.llnl.gov/RAJA/config_build.html .
I got the following error: 

[liao6@tux385:~/workspace/ASC-project/RAJA.git]./scripts/config-build.py 
Traceback (most recent call last):
  File "./scripts/config-build.py", line 85, in <module>
    assert os.path.exists( cachefile ), "Could not find cmake cache file '%s'." % cachefile
AssertionError: Could not find cmake cache file '/home/liao6/workspace/ASC-project/RAJA.git/host-configs/other/tux385.llnl.gov.cmake'.

Is this expected?

**Comment by DavidPoliakoff** [comment]
Hey @chunhualiao thanks for raising the issue! I've attempted to replicate the result. My steps were

```
1) git clone https://github.com/LLNL/RAJA.git
2) cd RAJA
3) ./scripts/config-build.py
```

And I saw no errors, getting a clean build. Does this looks like your process? Do you have CMake installed and working? I'm trying to see what is different in our environments and processes. Let me know if you see anything different, I'll try modifying my environment to replicate your error

**Comment by DavidPoliakoff** [comment]
@chunhualiao for a start, you could skip using the CS Toolkit build system and instead use CMake directly, does your use case require CUDA or is it pure CPU build? If it's pure CPU, you should be fine to just make a build directory and use CMake. We'll take a look at making the process you tried to use work, but the following should get you a build now

```
1) git clone https://github.com/LLNL/RAJA.git
2) cd RAJA
3) mkdir build
4) cd build
5) cmake -DCMAKE_INSTALL_PREFIX=[where you want to install RAJA] ..
6) make -j12
7) make install
```

**Comment by chunhualiao** [comment]
Thanks! 
Your steps are the same as mine. 
I switched to cmake and was able to proceed.

**Comment by DavidPoliakoff** [comment]
Wonderful. I'm out for the day, but if @davidbeckingsale is feeling ambitious we might look at making that configure script work, thanks for putting it through its paces
