### ISSUE TITLE
Supported compilers and versions

### ISSUE THREAD

**Issue by chunhualiao** [LLNL/RAJA#232]
Hi,
In the README.md, there is a line "Then, you can build RAJA like any other CMake project, provided you have a C++ compiler that supports the C++11 standard. ".

Can you list the compilers and version numbers recommended/tested for compiling RAJA?

Thanks!

**Comment by davidbeckingsale** [comment]
On Travis, we test with:

- gcc-4.9.4
- gcc-5.4.1
- gcc-6.2.0
- clang-3.6.0
- clang-3.7.0
- clang-3.8.0
