### ISSUE TITLE
Build failure with GCC 4.9.1 and CUDA 7.5.18

### ISSUE THREAD

**Issue by tomdeakin** [LLNL/RAJA#235]
The current head of develop branch (and tag v0.2.5) fails with GCC 4.9.1 and CUDA 7.5.18 with the following errors:
```
[ 92%] Building NVCC (Device) object examples/CMakeFiles/raja-pi.dir/raja-pi_generated_pi.cxx.o
/home/users/p02100/raja/include/RAJA/OffsetLayout.hxx:83:60: error: too many decimal points in number
                     std::array<IdxLin, sizeof...(RangeInts)> upper)
                                                            ^
/home/users/p02100/raja/include/RAJA/OffsetLayout.hxx: In constructor 'constexpr RAJA::internal::OffsetLayout_impl<VarOps::integer_sequence<I1 ...>, IdxLin>::OffsetLayout_impl(std::array<IdxLin, sizeof... (RangeInts)>, std::array<IdxLin, sizeof... (RangeInts)>)':
/home/users/p02100/raja/include/RAJA/OffsetLayout.hxx:83:94: error: parameter packs not expanded with '...':
                     std::array<IdxLin, sizeof...(RangeInts)> upper)
                                                                                              ^
/home/users/p02100/raja/include/RAJA/OffsetLayout.hxx:83:94: note:         'RangeInts'
CMake Error at raja-pi_generated_pi.cxx.o.cmake:262 (message):
  Error generating file
  /home/users/p02100/raja/build-apr21/obj/examples/CMakeFiles/raja-pi.dir//./raja-pi_generated_pi.cxx.o


make[2]: *** [examples/CMakeFiles/raja-pi.dir/raja-pi_generated_pi.cxx.o] Error 1
make[1]: *** [examples/CMakeFiles/raja-pi.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by trws** [comment]
RAJA is not tested as working with CUDA 7.5.  Upgrading to 8.0 should address this issue.

**Comment by tomdeakin** [comment]
I couldn't find it documented that you only support from CUDA 8. Can you please update your Readme with minimum, or at least tested, combinations of GCC, CMake and CUDA? For example, there is a very useful list for Kokkos https://github.com/kokkos/kokkos/blob/master/README

**Comment by trws** [comment]
Thank you for the feedback.  We only determined the incompatibility with 
7.5 in a recent release cycle, hence the late reply, and will document 
it shortly.  For the time being, the tested compilers on x86 are 
gcc4.9.3+ (with and without nvcc 8.0+), clang 3.7+, clang cuda in clang 
4.0 (experimental) and icc15+, on bgq the bgclang compilers are the only 
guaranteed fully supported target going forward but most functionality 
can be made to work with gcc version 4.8 on there as well.

**Comment by rhornung67** [comment]
@tomdeakin additional info on bgq compilers.  The current RAJA 'develop' will only build with bgclang 4.0.0 and later; specifically, r284961 and later. The gcc 4.8 compiler (on our BG/Q machines at least) is broken and will not be fixed. You may be able to get RAJA to build with it, but our apps cannot use it so we don't exercise it.

As @trws said, we will get this sort of thing documented soon. Not to make excuses, but we have been focusing on delivering features to our production apps. As a result, making information available to a broader user community tends to get neglected. @davidbeckingsale and I met this morning and assigned ourselves several documentation related tasks.

**Comment by rhornung67** [comment]
@tomdeakin I forgot to add, clang 3.7 will not compile several basic unit tests (mostly forallN related). You should be good with clang 3.8+.
