### ISSUE TITLE
Missing return

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#271]
I run my a static analysis tool on my code that uses RAJA, and it complained about a non-void function without a return statement. I am not sure exactly which function it was reporting; however, it's in include/RAJA/pattern/forall.hpp in the develop branch.
Manual inspection shows that forall_Icount on line 245 seems to have a non-void return type and no return. Similar situation on lines 317, 339, 354, 379, 402, 430, 455, 488, 513.
Looking at the definition of std::enable_if, it may be a limitation of the static analysis tool because it looks as though ::type is defined to be void.

**Comment by DavidPoliakoff** [comment]
Hey @tepperly ,

Any chance we could get the tool? It'd be interesting to see what it's doing.

Thanks for the bug report.

**Comment by rhornung67** [comment]
Thanks @tepperly will fix post-haste!

**Comment by willkill07** [comment]
from the compiler perspective, `std::enable_if_t<bool, T=void>` will either (a) have no type and cause SFINAE or (b) have the type `T`. When `T` is not specified, the return type will be void if the bool evaluates to true.

There's only one way I'm aware of to "fix" RAJA to still make it work with @tepperly 's static analysis tool, but it makes the code a little harder to digest. The last template argument in our template list could be:

`typename = typename std::enable_if<Condition>`

However, this will **not** work in instances where we use variadics as they must be listed last.

@tepperly Does your static analysis tool support SFINAE or understand the implicit T=void as the second template parameter for `std::enable_if`?

**Comment by davidbeckingsale** [comment]
Closing, this is a limitation of the static analysis tool.
