### ISSUE TITLE
Clang undefined reference to `RAJA::ReduceSum<RAJA::seq_reduce, double>::Reduce'

### ISSUE THREAD

**Issue by jeffhammond** [LLNL/RAJA#291]
I see this in https://travis-ci.org/ParRes/Kernels/jobs/258234377 and https://travis-ci.org/ParRes/Kernels/jobs/258234381.  I cannot reproduce locally because I have 8.1.0 (not 7.3.0) on my Mac and I do not see the issue on my Linux workstation with Clang 3.8.

Is this a RAJA bug or is it a toolchain issue?

```
+make -C Cxx11 stencil-vector-raja transpose-vector-raja
make: Entering directory `/home/travis/build/ParRes/Kernels/Cxx11'
clang++-3.8 -std=c++11 -pthread  -DPRKVERSION="2.16" stencil-vector-raja.cc -DUSE_RAJA -I/home/travis/build/ParRes/Kernels/PRK-deps/raja/include -L/home/travis/build/ParRes/Kernels/PRK-deps/raja/lib -lRAJA -lpthread -ldl -o stencil-vector-raja
/tmp/stencil-vector-raja-3fd450.o: In function `RAJA::ReduceSum<RAJA::seq_reduce, double>::~ReduceSum()':
stencil-vector-raja.cc:(.text._ZN4RAJA9ReduceSumINS_10seq_reduceEdED2Ev[_ZN4RAJA9ReduceSumINS_10seq_reduceEdED2Ev]+0x1c): undefined reference to `RAJA::ReduceSum<RAJA::seq_reduce, double>::Reduce'
/tmp/stencil-vector-raja-3fd450.o: In function `RAJA::ReduceSum<RAJA::seq_reduce, double>::operator+=(double)':
stencil-vector-raja.cc:(.text._ZN4RAJA9ReduceSumINS_10seq_reduceEdEpLEd[_ZN4RAJA9ReduceSumINS_10seq_reduceEdEpLEd]+0x6): undefined reference to `RAJA::ReduceSum<RAJA::seq_reduce, double>::Reduce'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [stencil-vector-raja] Error 1
```

**Comment by davidbeckingsale** [comment]
@willkill07 ?

**Comment by willkill07** [comment]
Let me test this on my Mac where I have clang-3.8 installed. FYI Reduce is a type alias -- there is no reason for it to not exist.

**Comment by willkill07** [comment]
This must be some weirdness with the toolchain. I only have access to 3.8.1 and that builds just fine (without openmp). 3.9, 3.9.1, 4.0.0 all build your code in full.

I've also tested spack builds of 3.8.1, 3.9.1, and 4.0.0 (with openmp enabled)

**Comment by willkill07** [comment]
@davidbeckingsale and @jeffhammond -- I've been thinking about this.

Due to the one-off nature, I don't think it's something we can really fix since it seems like compiler non-compliance with AppleClang. I've tested on all versions that I have access to without failure (even on my system @ LLNL where I do have 7.3.0).

I'm placing this under `wontfix` -- Travis allows the installation of pure clang compilers through brew. AppleClang doesn't even have OpenMP support, severely restricting the usefulness of RAJA.
