### ISSUE TITLE
GPUforallN-strided test failing

### ISSUE THREAD

**Issue by willkill07** [LLNL/RAJA#296]
I was running tests on the current develop tag and found that GPUforallN-strided test was failing.

Problem was not present in 1286dd7 but first appeared with 91d4798

```
$ srun -n1 -pp100 ./test/unit/gpu/test-GPUforallN-strided.exe -V
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from forallN
[ RUN      ] forallN.rangeStrides
/g/g19/killian4/RAJA/test/unit/gpu/forallN-strided.cpp:90: Failure
Value of: 0
Expected: arr[inner]
Which is: 500
/g/g19/killian4/RAJA/test/unit/gpu/forallN-strided.cpp:90: Failure
Value of: 0
Expected: arr[inner]
Which is: 501
/g/g19/killian4/RAJA/test/unit/gpu/forallN-strided.cpp:90: Failure
Value of: 0
Expected: arr[inner]
Which is: 500
[  FAILED  ] forallN.rangeStrides (746 ms)
[----------] 1 test from forallN (746 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (746 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] forallN.rangeStrides

 1 FAILED TEST
```

**Comment by davidbeckingsale** [comment]
I guess @ajkunen's 'RangeStrideSegmentFix' branch wasn't necessarily a fix 😄

**Comment by ajkunen** [comment]
Does our github testing not run GPU tests?

**Comment by DavidPoliakoff** [comment]
I don't know if we have Bamboo up, but Travis definitely doesn't. We test compilation, but not whether they run correctly

**Comment by willkill07** [comment]
We can only compile NVCC through Travis CI, not run :(

**Comment by ajkunen** [comment]
rats

**Comment by ajkunen** [comment]
ok, I'll fix it

**Comment by MrBurmark** [comment]
Index calculation in the failing test is wrong too.
It should be  `int val = y * x * i + x * j + k;`.
This causes a segfault as the indices are still wrong.
It looks like forallN is getting the wrong distance when it has a RangeStrideSegment with a cuda policy. It appears to get the distance from begin to end you would get ignoring stride.

**Comment by ajkunen** [comment]
I don't think the index calc is wrong.

It's using z,y,x for sizes of i,j,k, respectively.  Which is odd, but not incorrect.

**Comment by ajkunen** [comment]
It appears to be in RAJA/policy/cuda/policy.hpp, where it's computing the number of iteration in each dimension using std::distance(std::begin(i), std::end(i)).

Instead of getting the number of iterations between begin() and end(), it's getting the numeric distance.

**Comment by willkill07** [comment]
Per the C++ standard: 

§ 24.4.4/4
```
distance():
Eﬀects: If InputIterator meets the requirements of random access iterator,
returns (last - first); otherwise, returns the number of increments needed 
to get from first to last
```

RangeStrideSegment iterators are RandomAccessIterators

Perhaps the bug is with operator-() ?

**Comment by ajkunen** [comment]
it is.  I should have a fix for this today.

**Comment by trws** [comment]
On this topic, anyone want to take a crack at setting up either coriander to compile our cuda code to OpenCL for Travis testing or getting Jenkins or similar working on AWS so we can actually have the cuda tests run?
