### ISSUE TITLE
forallN development tasks

### ISSUE THREAD

**Issue by ajkunen** [LLNL/RAJA#3]
@trws 
- [x] Eliminate Code Gen (#4) 
- [x] Intel compiler issues (slowness in compiling, performance issues) (#5)
- [x] Clang OpenMP (backed out in commit ceca2c61d46d5c44f298696b405675f25883cd90 ??? need to hunt down specific commit?)
- [ ] nvcc lambda "introspection???" (need to generate a branch for this)
- [ ] add static_assert's to help the user out!
- [ ] add sequential tests for CPU nested and CPU nested reduce tests so the forallN machinery gets tested for all configurations (i.e., without OpenMP enabled)

**Comment by davidbeckingsale** [comment]
@ajkunen which of these would you consider required still?

**Comment by trws** [comment]
Hmm... We probably still need more testing.  I checked off a couple that I'm certain have been dealt with.

**Comment by davidbeckingsale** [comment]
Thanks! What does "nvcc lambda introspection" mean?

I will break out the others into separate issues.

**Comment by trws** [comment]
I'm not sure actually, Adam do you recall?

Sent from my iPad

On Mar 14, 2017, at 10:29 AM, David Beckingsale <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! What does "nvcc lambda introspection" mean?

I will break out the others into separate issues.

**Comment by ajkunen** [comment]
In C++ you can extract the type of the arguments to a lambda.  I had tried this (successfully) to adopt the index type of the lambda, instead of having to specify them to forallN.

This was completely broken with device lambdas (a year ago).

This isn't a high priority, but I believe that Tom Deakin was thinking along these lines for the forall() and the use of RAJA::Index_type.

**Comment by davidbeckingsale** [comment]
Got it, I'll break that out to a separate issue.
