### ISSUE TITLE
Add an "Enhancement" label

### ISSUE THREAD

**Issue by willkill07** [LLNL/RAJA#303]
It would be nice to be able to label issues/PRs as enhancements -- ones that don't necessarily provide new features, but improve the implementation of RAJA and its components.

**Comment by rhornung67** [comment]
Agreed. I'm thinking about adjusting the labels specifically for labeling PRs. If we adopt different review policies for different types of PRs (e.g., a bugfix vs. an API change that impacts users), this would help. I don't know of any other way to associate PRs to different levels of review scrutiny.

**Comment by trws** [comment]
Done.

On another topic @rhornung67, look at code owners, it's a new feature but assigns people based on what gets touched and who "owns" that area of the code, so more sensitive areas get more review and people who know that area get assigned.
