### ISSUE TITLE
factor out use of std::array in layouts

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#313]
Using std::array can cause cuda failure in certain corner-cases.  Specifically when operator[] doesn't inline and either of --expt-relaxed-constexpr and -std=c++14 is missing.  With both of those it works deterministically, without one it can fail, and either way should really be factored out.

**Comment by willkill07** [comment]
Would this be addressed with camp or something along the lines of `Index_type[static Dims]`?

**Comment by trws** [comment]
I just dug into this some more.  It looked at first like taking 
static-length const arrays would do the job, but it makes it so that 
passing a std::array is an error, which is really unfortunate.  I have 
an idea for how to make this all work much nicer, but it needs to wait 
for camp to merge.  Basically, a variant on the str_const concept, have 
a type that can take a statically-sized const array for initializer 
lists, or a std::array and convert them into a common constant array 
type we can deal with internally.

**Comment by rhornung67** [comment]
@twrs I don't have any reasonable ideas about what to do here except leave as-is for now, then think about it some more if it becomes an issue in a production application. Do you know specifically under which circumstances '[]' fails to inline?

**Comment by trws** [comment]
That issue in particular is gone now I think, because even if it 
doesn’t inline we’re referencing a statically sized array in the 
struct now rather than a std::array.  The std::array only remains in the 
host-side interfaces.

**Comment by rhornung67** [comment]
OK. If you want to close the issue, that's OK with me.   If @ajkunen and others are comfortable with the usage of std::array in the interface, that works for me.
