### ISSUE TITLE
OpenMP policies are using the wrong values

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#34]
At the least, the segment iteration policies use `omp_get_max_threads()` where it should be using `omp_get_num_threads()`.  This works on some implementations, but it will break on others.

See here: https://github.com/LLNL/RAJA/blob/develop/include/RAJA/exec-openmp/forall_openmp.hxx#L970

**Comment by davidbeckingsale** [comment]
It seems like there are a lot of cases where `omp_get_max_threads()` is used to get the number of threads. I have switched fixed the case you pointed at out in #36
