### ISSUE TITLE
Latest commit to master breaks laser simulation

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#343]
include/camp/lambda.hpp:126:24: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(bind_front);

include/camp/list/find_if.hpp:84:21: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(find_if);
                     ^

VarOpinclude/camp/camp.hpp:147:24: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(accumulate);

include/camp/camp.hpp:168:20: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(filter);
s::integer_sequence replaced by VarOps::index_sequence.

**Comment by tepperly** [comment]
I submitted a pull request that resolves this issue.

**Comment by tepperly** [comment]
FYI, I am planning to resolve the VarOps::index_sequence issue by changing the laser simulation.

**Comment by trws** [comment]
This is all set right @tepperly?

**Comment by tepperly** [comment]
Yes. We're fully functional.
