### ISSUE TITLE
RAJA ignores BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by tepperly** [LLNL/RAJA#349]
In the past, I could build a shared RAJA library libRAJA.so by including a BUILD_SHARED_LIBS setting in the cmake command line.
```sh
cmake -DBUILD_SHARED_LIBS=On ..
```
Now RAJA's build always makes libRAJA.a.  I guess this may be a BLT issue.

**Comment by davidbeckingsale** [comment]
Whoops, you could be right. Can you try using the option ENABLE_SHARED=On when running CMake?

**Comment by tepperly** [comment]
I see from the BLT code that ENABLE_SHARED may do the trick. However, FWIW BUILD_SHARED_LIBS is the normal cmake way to do that.

**Comment by davidbeckingsale** [comment]
Yeah, BLT should support the standard. If this works, could you please file a BLT issue.

**Comment by tepperly** [comment]
Using 
```sh
cmake -DENABLE_SHARED_LIBS=On
```
causes RAJA's build to make the shared library version. I'll submit a BLT issue.
