### ISSUE TITLE
Add RAJA::make_tuple

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#351]
Helper for nested forall invocation.

**Comment by willkill07** [comment]
Is this as easy as I think it is? Going from memory:

```cpp
namespace camp {
template <typename ... Types>
CAMP_HOST_DEVICE
auto make_tuple(Types&& ... args) -> camp::tuple<camp::decay<Types>...> {
  return camp::tuple<camp::decay<Types>...>(camp::forward<Types>(args)...);
}
} // end namespace camp
```

**Comment by trws** [comment]
Even easier.  The camp:: namespace already has one, it just needs to be 
aliased as something appropriate for RAJA, preferably more 
self-documenting than make_tuple actually, to make nested::forall 
invocations more parsable.

**Comment by artv3** [comment]
@rhornung67 we added this in recently right?

**Comment by rhornung67** [comment]
Yup.
