### ISSUE TITLE
non-loop executors for nested, particularly OMP parallel

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#353]
For an initial version, all we need is a specialization of `nested::Executor` for `OMP_Parallel`, or preferably `omp_parallel`, or even better yet `RAJA::omp::parallel`.  All the operator should need to do is this:

```c++
#pragma omp parallel
body();
```

**Comment by artv3** [comment]
@trws , @ajkunen , should I hold off on RAJA region until the new nested framework is in or is this something I can do within the existing framework?

**Comment by ajkunen** [comment]
I think you could go ahead with trying to make a RAJA::region() function..

This API call should be independent of how we end up working it into the nested loop stuff.

I would just stay away from any of the RAJA::nested::* until that work is merged in.


-Adam

**Comment by rhornung67** [comment]
@artv3 Ditto on what @ajkunen said.  As a first test of this, we have two kernels in the RAJA Perf Suite that would benefit from opening an OpenMP parallel region and then launching the loops inside it with an omp for nowait policy.

**Comment by trws** [comment]
One thing I’d say here, as a test of whatever you do, refactor the 
existing internal omp parallel to use it.  That should give it a decent 
sanity check for interactions with everything else.

**Comment by ajkunen** [comment]
So I'm assuming we all agree this should look something like:
```

RAJA::region<policy>([=](){

 // Some code 

});
```

**Comment by rhornung67** [comment]
That's what I am thinking.

**Comment by artv3** [comment]
I think OMP should be in the namespace since this is an OMP specific feature. A user might try to use a CUDA policy.

**Comment by rhornung67** [comment]
@artv3 I would think that we would have to do a specific specialization for each policy type. If we don't provide a generic implementation, then unsupported usage would not compile.

**Comment by rhornung67** [comment]
@artv3 can this issue be closed?

**Comment by artv3** [comment]
Yup, I'll close it.
