### ISSUE TITLE
establish the interface for `RAJA::region`

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#354]
This is related to #353, either the executors in #353 should be set up to use RAJA::region or the reverse.  If we decide to use functions for this, the nested executors should probably be refactored to be extensible the same way that forall_impl now is, by ADL.

**Comment by rhornung67** [comment]
@trws, @artv3 I think this is resolved now. Can this issue be closed?

**Comment by trws** [comment]
Yup, looks like it.
