### ISSUE TITLE
fix overload resolution of nested::forall

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#355]
Write the "enable_if" rules, or whatever it ends up needing to be, to resolve the conflict between the generic 3-argument forall at the RAJA:: level with nested::forall.

**Comment by trws** [comment]
Actually, this is already resolved so I'm closing.  If begin end index variants are deprecated or removed we could remove a good bit of enable_if cruft though, so it might be good to have an issue for that if and when that happens.

**Comment by rhornung67** [comment]
@trws I added a JIRA issue for this.
