### ISSUE TITLE
-DENABLE_APPLICATIONS=On absent from CMakeFile

### ISSUE THREAD

**Issue by cyr6** [LLNL/RAJA#362]
Hello,

I was trying to compile the examples in [RAJA-examples](https://github.com/LLNL/RAJA-examples) but could not succeed.

Neither ENABLE_APPLICATIONS nor RAJA_ENABLE_APPLICATIONS seem to appear anywhere in the Git. Passing these options in CMake results in CMake informing these variables aren't used. Is there a step-by-step guide to follow to compile the RAJA-examples?

Thanks,
Cyril

**Comment by davidbeckingsale** [comment]
Hey @cyr6, we are currently in the process of restructuring our RAJA proxy application examples. The current [examples](https://github.com/LLNL/RAJA-examples) are now deprecated.

I'll update this issue once we have released the new repository, should be in the next few weeks.

In the meantime, you can check out an older RAJA release ([0.3.1](https://github.com/LLNL/RAJA/tree/v0.3.1))  and the `RAJA_ENABLE_APPLICATIONS` option will still work.

**Comment by cyr6** [comment]
Alright, thanks for your answer.

Have a nice day/evening,
Cyril

**Comment by davidbeckingsale** [comment]
Examples can now be found here: https://github.com/LLNL/RAJAProxies
