### ISSUE TITLE
omp_get_max_threads in forall_segments

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#37]
Our use of omp_get_max_threads in forall_segments is questionable.  For example, it may do the wrong thing if environment variables are not properly set. Look into this more carefully to determine a more robust solution.

**Comment by davidbeckingsale** [comment]
Noting @trws comment from #36 :

> Maybe limit it to some multiple of std::thread::hardware_concurrency by default? In general, omp_get_max_threads() inside a parallel region should be ok (it was limit threads I was thinking of before, but max_threads in this context is not really safe either) but where we use what is something we'll have to keep an eye on.

**Comment by davidbeckingsale** [comment]
I believe this issue has been addressed.
