### ISSUE TITLE
RAJA::nested::forall versus RAJA::forallN (stupid user looking for docs)

### ISSUE THREAD

**Issue by jeffhammond** [LLNL/RAJA#383]
I am having a hard time understanding the difference(s) between `RAJA::forallN` and `RAJA::nested::forall`.  Is the latter replacing the former?  The docs I can see (https://software.llnl.gov/RAJA/index.html) do not yet discuss RAJA::nested and Google points me to https://asc.llnl.gov/DOE-COE-Mtg-2016/talks/2-07_Kunen.pdf, which is interesting but doesn't address RAJA::nested either.

Thanks.

**Comment by ajkunen** [comment]
the RAJA::nested::forall is currently getting rewritten in the feature/kunen1/nested2 branch... and will eventually replace forallN.

It is engineered quite differently to address performance issues, and also provides the ability to do more complex looping strategies that will allow the use of GPU shared memory.

It will eventually be documented in a user guide, and hopefully a publication at some point.  

it's still fairly in flux.

**Comment by artv3** [comment]
@jeffhammond a preliminary one is found here http://raja.readthedocs.io/en/feature-user-docs/

**Comment by rhornung67** [comment]
@jeffhammond I am currently rewriting our example codes and the tutorial section of the document that @artv3 pointed you to.  A reasonable draft that will help you understand what's going on should be available by the middle of next week, if not sooner -- depends if my wife will object to me working on my laptop while she's unwrapping Xmas presents...:-)

**Comment by jeffhammond** [comment]
Thanks.  I don't expect to do much with Kripke until January 3.  I converted RAJA::nested::forall to raw OpenMP in Kripke for testing purposes for now.

**Comment by rhornung67** [comment]
@jeffhammond RAJA::forallN will be deprecated soon. RAJA::nested is what we currently support (see nested loop sections of tutorial here for a reasonable discussion: 
http://raja.readthedocs.io/en/latest/tutorial.html)

@ajkunen is working on a rework to improve and expand on RAJA::nested. That will eventually replace RAJA::nested and Kripke will be converted.
