### ISSUE TITLE
RAJA assumes linux

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#40]
There are a few places in the repository that use "sched_*" or linux-specific timer interfaces.  It would be good to shift, or at least add a fallback, to C++11 standard alternatives to these.  Examples:
- `sched_yield()` -> `std::this_thread::yield()`
- `clock/gettime/etc.` -> `std::chrono::...`

**Comment by rhornung67** [comment]
Good point.  Are the C++ std methods robust everywhere; e.g., will std::this_thread::yield work with any threading model?

**Comment by trws** [comment]
Short of CUDA, yes.  They're portable anywhere a full C++11 implementation can be assumed.  That doesn't mean they wont necessarily have slightly different behaviors due to details of implementation, but at least they'll exist and do something close to what we want

**Comment by rhornung67** [comment]
Will the std::chrono::... stuff report the correct timing for a multi-threaded code?  For example, clock_t reports an aggregate time summed over all threads on typical linux systems (interestingly, it does the right thing on BG/Q -- go figure).

**Comment by trws** [comment]
std::chrono is all meant to be duration, or wall clock, time depending on the timer you select, and actually doesn't have an interface for "CPU time" like clock.  It would be worth double checking, but at the very least chrono::system_clock will definitely give wall time, while either high_resolution_clock or steady_clock (monotonic's equivalent) should give an implementation-defined representation of a high-resolution duration.  The nice thing about this, is we don't actually have to care about what that representation is, they come with "casts" to meaningful time quantities that are also portable.
