### ISSUE TITLE
Document or remove prototypes with unclear purpose or usage

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#41]
I've noticed a couple of outward-facing functions that puzzle me.  Thoughts/history @keasler, @rhornung67?
- `forall_segments`: this has definitions in a couple of places, but is not used by anything in raja itself.  Is this a deprecated usage, or something in active use?
- `void forall(const INDEXSET_T& iset, LOOP_BODY loop_body)`: This takes any first argument at all and treats it as an indexset.  Is there an assumption someplace that custom IndexSet types do not need to inherit from IndexSet?

**Comment by keasler** [comment]
forall_segements is used for the CPU version of CoMD only.  Once IndexSet Objects are supported on the GPU, then forall_segments will be deprecated, and replaced with a stream construct.

The first implementation of forall_segments worked with an omp parallel for schedule(static,1), which was not realistic for dispatching 'task' segments to streams.  The second cut used a parallel region, and I believe the third cut allowed for each stream to act independently, with any amount of work per stream.  I have never reviewed the later two implementations, so I'm not sure I believe they are strictly correct.

**Comment by keasler** [comment]
So, in effect, all the forall_segment code is currently unused or will be deprecated.

**Comment by trws** [comment]
Makes sense, thanks @keasler.  What about the `INDEXSET_T` templates?

**Comment by davidbeckingsale** [comment]
Looking at this, I think we can remove `forall_segments`.
I believe the `INDEXSET_T` stuff is gone already.

I'll make a branch to deal with this.

**Comment by trws** [comment]
Yeah, the INDEXSET_T templates were superseded by the iterables stuff, so cleaning up the _segments stuff should take care of it.

**Comment by rhornung67** [comment]
We still haven't reworked the IndexSet implementation to work on the GPU. I believe that was necessary to deprecate forall_segments.

**Comment by trws** [comment]
Since variant made it into c++17, that's probably a good way to take care of the indexset issue: http://en.cppreference.com/w/cpp/utility/variant

**Comment by trws** [comment]
Rather, it would be a good way to make indexset use no virtuals, but would restrict it to the types listed in the variant type.  Since that's already a restriction in the current implementation, we can probably deal with it.

**Comment by davidbeckingsale** [comment]
@rhornung67 - none of the segments code was implemented for the GPU, so I'm not sure what you mean.
