### ISSUE TITLE
CUDA 9 Warnings

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#424]
@davidbeckingsale @rhornung67,  Could we setup CUDA 9 in Travis? I found warnings that appear in CUDA 9 but not in 8. Looking to fix them at the moment.

**Comment by rhornung67** [comment]
I don't know why we couldn't. However, it's best to build with multiple compiler versions to remove warnings before committing them.

**Comment by artv3** [comment]
PR #426 removes the warnings.
