### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/RAJA#43]
Hey guys,

Out today, but noticed the links in the readme on github are broken. Oof. Will fix tomorrow if one of you enterprising souls doesn't do it first

**Comment by davidbeckingsale** [comment]
Which links?

**Comment by DavidPoliakoff** [comment]
If you look at the main github page for RAJA, look at the link for Kokkos. It's not a hyperlink, there's a formatting issue

**Comment by davidbeckingsale** [comment]
This should be fixed. Check and close if I've addressed all the issues.

**Comment by DavidPoliakoff** [comment]
Thanks! :beers:
