### ISSUE TITLE
force cache for RAJA_LOADED breaks things

### ISSUE THREAD

**Issue by ajkunen** [LLNL/RAJA#430]
https://github.com/LLNL/RAJA/blob/d329c9e91b86dfdb4f62bf91464e8b2faa60c03c/CMakeLists.txt#L25

So if we put RAJA_LOADED into cache, then it breaks if CMake ever decides to reconfigure... like after using ccmake... or a change to a CMakeLists.txt file.

Is this necessary?

**Comment by davidbeckingsale** [comment]
Oh whoops. Basically we need to be able to set the RAJA_LOADED variable in all scopes - I don't know if just using PARENT is enough. That would be the fix for now.

**Comment by ajkunen** [comment]
ugg.. I'm not sure what the cmake magic for that is.  @white238 would know.
