### ISSUE TITLE
CUDA Policy file seems overfull

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/RAJA#442]
Hey folks,

I'm writing software that wants to include a small amount of RAJA's CUDA stuff, mostly just the names of [policies](https://github.com/LLNL/RAJA/blob/develop/include/RAJA/policy/cuda/policy.hpp#L123).

Unfortunately, if you include that header file, you immediately get into things which require knowledge of blockIdx. Now, I can include the CUDA headers to get those, but it would be nice if we could at least include policy names in a header that is parsable by a general compiler.

A resolution would be a CUDA policy.hpp that could be included in a project compiled with gcc and compiled, moving things which require CUDA to more protected headers.

**Comment by davidbeckingsale** [comment]
I've noticed this before also, the main issue is the forallN policies that require some of those structs as template parameters (where the policy actually contains implementation details rather than just being a tag type). This might be addressed with `nested`? @ajkunen

**Comment by DavidPoliakoff** [comment]
For just a temp fix solution, I'm adding a definition to my RAJA branch which ifdefs out the policies nested requires, that seems to do the trick

**Comment by rhornung67** [comment]
@ajkunen I would say that your recent coda policy changes address this issue. Do you agree? Should we wait until forallN is excised?

**Comment by ajkunen** [comment]
Two things: we need to excise forallN and the old Shmem stuff.  Both of those should greatly cleanup the cuda policy file.

forallN is currently deprecated, what is our plan for removal?  Is it too early?

**Comment by rhornung67** [comment]
Resolved. Changes in v0.7.0 release.
