### ISSUE TITLE
Atomic max/min has poor code for CPU

### ISSUE THREAD

**Issue by jcownie-intel** [LLNL/RAJA#447]
The code for atomic max on the CPU misses an important optimization. It treats these operations as being identical to others implemented with CAS, like this (from atomic_builtin.hpp)
```C++
template <typename T>
RAJA_INLINE T atomicMax(builtin_atomic, T volatile *acc, T value)
{
  return detail::builtin_atomic_CAS_oper(acc, [=](T a) {
    return a > value ? a : value;
  });
}
```
This code always performs a CAS operation, however, for max and min most values do not need to perform any update because our contribution (`value`) is the wrong side of the running value (`*acc`). In that case no update is required. (If I am doing a max and my contribution is 6 when the running value is already 15, I don't need to write anything!)

Theoretically one can shows that the number of atomics expected (the mean over all possible permutations) increases only logarithmically with the number of contributions, like this

Length | Expected cmpxchgs
-------|------
2|1.50
3|1.83
4|2.08
5|2.28
6|2.45
7|2.59
8|2.72
9|2.83
10|2.93
20|3.60
30|3.99
40|4.28
50|4.50
60|4.68
70|4.83
80|4.97
90|5.08
100|5.19
200|5.88
300|6.28
400|6.57
500|6.79
600|6.97
700|7.13
800|7.26
900|7.38
1000|7.49
1500|7.89
2000|8.18
3000|8.58
4000|8.87
5000|9.09

What is needed is to have a new version of the builtin_atomic_CAS_operator which takes a condition as well as a mutator. (While a test here before invoking the CAS would catch many cases, better is to move the test inside, since after a failed CAS we may still be able to return without executing a CAS if the running value is now past our contribution).

**Comment by trws** [comment]
Quite so, thanks for pointing this out Jim.  We should be able to apply that to all of the backends, with the possible exception of cuda because of the weak memory model.

**Comment by jcownie-intel** [comment]
Excellent, thanks. 
I'd like to be able to contribute a patch, but 
1.  time is in short supply
2. by the time I work out how to get permission to contribute and leap through Intel legal's hoops you'll probably have fixed it anyway :-)
