### ISSUE TITLE
duplicate aliases

### ISSUE THREAD

**Issue by liu15** [LLNL/RAJA#453]
Older Intel compilers (Intel 15) fail with the following error.

/include/camp/camp.hpp(227): error: "as_list" has already been declared in the current scope
  using as_list = typename as_list_s<T>::type;
        ^
 
As far as I can tell, the using as_list is declared in both tuple.hpp and list.hpp, both of which are included from camp_aliases.hpp.

Obviously the Intel 15 compiler is pretty old (three versions behind).  However, it seems like the declaration of this alias twice was not the original intent and points this alias being in the wrong place.

**Comment by trws** [comment]
Yup, we can clean that up.  I will note that we don't explicitly support icc15, but there's no reason not to fix this anyway.
