### ISSUE TITLE
"here 2" stdout pollution

### ISSUE THREAD

**Issue by jeffhammond** [LLNL/RAJA#468]
https://github.com/LLNL/RAJA/blob/develop/include/RAJA/pattern/forall.hpp#L519 causes my Travis logs to be full of "here 2" lines that go on for miles (https://travis-ci.org/ParRes/Kernels/jobs/370896285).

I assume it was an accident to leave this debug message in the mainline code.

**Comment by davidbeckingsale** [comment]
Yup 😢 - will get it fixed! Thanks for reporting.

**Comment by davidbeckingsale** [comment]
@artv3 - can you remove the print statement you added?
