### ISSUE TITLE
Document __host__ __device__ problems

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/RAJA#475]
Hey folks,

We have a problem in that users often think `__host__ __device__` lambdas are a great idea. This isn't a bug in RAJA, but we are the place users will encounter it, and they are more likely to say it's us being slow. We might want to just put up warning signs around that, I don't know how or where though

**Comment by rhornung67** [comment]
Probably makes most sense to document it in the user guide. I will take care of it.

**Comment by MrBurmark** [comment]
#481

**Comment by rhornung67** [comment]
Thanks @MrBurmark

**Comment by rhornung67** [comment]
Done in v0.6.0rc3 docs on read the docs.
