### ISSUE TITLE
External lib reduce compile error

### ISSUE THREAD

**Issue by mclarsen** [LLNL/RAJA#476]
When compiling a reduction with cuda in my own lib, I encountered this error:

`include/RAJA/policy/cuda/reduce.hpp(215): error: the global scope has no "__shfl_xor"`

and something similar for `__shfl`. Any ideas what causes this?

**Comment by davidbeckingsale** [comment]
Are you compiling everything through `nvcc`? What compilers and versions are you using?

**Comment by mclarsen** [comment]
I am using `nvcc` gcc4.9.3 and cuda 8.0. I believe this intrinsic does not exist for older GPU archs. After restricting the arch to 3.0 (by default it compiles everything), the error goes away. I think it would be helpful to add a note in "requirements" about the minimum compute architecture that us supported.

**Comment by mclarsen** [comment]
This knowledge is baked into `RAJA_NVCC_FLAGS`, and had I used that from the start, I would not have run into this issue.

**Comment by DavidPoliakoff** [comment]
I've run into this myself in the past, I wonder whether we could get a hook in RAJA to avoid this... I'll look it up. Would be neat if NVCC exported the arch it's compiling for

**Comment by rhornung67** [comment]
@davidbeckingsale or @MrBurmark do either of you know if this issue is resolved?

**Comment by MrBurmark** [comment]
We could add an sm arch version check in the configure file to catch if you're using an unsupported cuda arch such as 2.0.

**Comment by rhornung67** [comment]
@MrBurmark it is noted in the user guide that sm_35 is the minimum level required to use all RAJA features and we set CUDA_ARCH to sm_35 in the top-level CMakeLists.txt file as a default. Of source this can be overridden by passing -DCUDA_ARCH=sm_60, for example to CMake.  Is that sufficient?

**Comment by MrBurmark** [comment]
That's probably fine if we always set it and note that we do not support below sm_35.
