### ISSUE TITLE
tuple_cat_pair for default case (no special idx_seq)

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/RAJA#479]
Would be nice to have a version of tuple_cat_pair https://github.com/LLNL/RAJA/blob/develop/include/camp/tuple.hpp#L369 which doesn't need the idx_seq's for the case where we just want idx_seq<n> for each

**Comment by DavidPoliakoff** [comment]
@trws

**Comment by trws** [comment]
This exists now, on my bugfix branch for tuple_cat, could you take a look there and see if that's what you want?

**Comment by rhornung67** [comment]
@DavidPoliakoff does Tom's branch address the use case you have in mind?

**Comment by DavidPoliakoff** [comment]
Yep, this works, closing

**Comment by rhornung67** [comment]
Thanks!
