### ISSUE TITLE
Document inability to break from RAJA forall

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/RAJA#483]
More generally: document where a RAJA lambda loop body differs from a for loop, things like continue and break. Getting these questions over IM.

**Comment by DavidPoliakoff** [comment]
That would be a good place to put this stuff, yeah

**Comment by davidbeckingsale** [comment]
For things like `break` and `continue` I guess what we need is just a reminder that it is a function, not a loop, so you can't use those constructs.

**Comment by rhornung67** [comment]
Got it. Working these things into the user guide now.

**Comment by rhornung67** [comment]
Done in v0.6.0rc3 docs on read the docs.
