### ISSUE TITLE
RAJAStream make issue

### ISSUE THREAD

**Issue by nanzifan** [LLNL/RAJA#490]
Hi,
I'm a new student intern in LLNL. While I'm trying to make RAJAStream, it goes 'fatal error: RAJA/RAJA.hxx: No such file or directory'. 

I've already installed the RAJA and export the RAJA_HOME as RAJA install path, and tried both "#include RAJA/RAJA.hxx" and "#include RAJA/RAJA.hpp" in RAJAStream.hpp, I still get the issue. Did I miss something when install RAJA? Please help me with this problem.

The RAJAStream.cpp is here:
[https://github.com/UoB-HPC/BabelStream/blob/master/RAJAStream.cpp](url)

The full make error comes like this:

> make -f RAJA.make 
Set TARGET to change to offload device. Defaulting to CPU.
Available targets are:
  CPU (default)
  GPU
Set COMPILER to change flags (defaulting to GNU).
Available compilers are:
  INTEL GNU CRAY XL
g++ -DRAJA_TARGET_CPU -O3 -std=c++11 -fopenmp -DUSE_RAJA -I/home/znan/raja/raja/include main.cpp RAJAStream.cpp  -L/home/znan/raja/raja/lib -lRAJA -o raja-stream
In file included from main.cpp:31:0:
RAJAStream.hpp:12:26: fatal error: /RAJA/RAJA.hpp: No such file or directory
compilation terminated.
In file included from RAJAStream.cpp:8:0:
RAJAStream.hpp:12:26: fatal error: /RAJA/RAJA.hpp: No such file or directory
compilation terminated.
RAJA.make:53: recipe for target 'raja-stream' failed
make: *** [raja-stream] Error 1

**Comment by DavidPoliakoff** [comment]
Hey @nanzifan , we updated the header names a while ago, RAJA/RAJA.hpp is now the correct header. I tried to follow the link to your source file, but got a 404. Could you give a link to an updated file we could debug from? Thanks!

**Comment by nanzifan** [comment]
@DavidPoliakoff , this link should works [https://github.com/UoB-HPC/BabelStream](url), directly click the link seems doesn't work, but copy the link to browser works.

**Comment by DavidPoliakoff** [comment]
@nanzifan , I would look at the directory `/home/znan/raja/raja/include`, I think it must be a matter of your install if you can't pick up RAJA/RAJA.hpp. Are you `#include`'ing `RAJA/RAJA.hpp` or `/RAJA/RAJA.hpp` ? That seems ambiguous from the error log you gave

**Comment by nanzifan** [comment]
Hi, @DavidPoliakoff 
Here is the directory.
> znan@volta-v100-8core-30g:~/raja/raja/include$ ls
camp  cub  examples  experimental  gtest  RAJA  test  tune
And RAJA folder:

> znan@volta-v100-8core-30g:~/raja/raja/include/RAJA$ ls
config.hpp  index  internal  module.modulemap  module.private.modulemap  pattern  policy  RAJA.hpp  util

I use `#include RAJA/RAJA.hpp`, this line of code is in RAJAStream.hpp in the github code, and it's originally `#include RAJA/RAJA.hxx`, and I've changed it to .hpp, I didn't change anything else.

**Comment by DavidPoliakoff** [comment]
@nanzifan : I only ask because if you look at your build error

`
In file included from RAJAStream.cpp:8:0:
RAJAStream.hpp:12:26: fatal error: /RAJA/RAJA.hpp: No such file or directory
`

If you see that first `/` before RAJA (not RAJA.hpp, but RAJA), that appears to be a typo from something like a `#include</RAJA/RAJA.hpp>. If that's just an artifact from pasting to Github, let me know, but I want to debug that case first, this is a bizarre error otherwise.

**Comment by nanzifan** [comment]
@DavidPoliakoff You are write, it's a typo, the compile works this time. I didn't notice that before, my mistake. Thank you very much.

**Comment by DavidPoliakoff** [comment]
@nanzifan Would you be opposed to my closing this issue?

**Comment by nanzifan** [comment]
@DavidPoliakoff No problem, you can close it, thanks again for your help.
