### ISSUE TITLE
Add a check for CUDA_ARCH before defining cuda atomic functions

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#500]
Correct compilation issues in some cases.

**Comment by davidbeckingsale** [comment]
This can be reproduced by compiling without an `arch` flag, when the default is too low.

**Comment by rhornung67** [comment]
I will add a JIRA issue to start a "recommended usage" (or some appropriate name) section in the user guide to document platform-specific and non-specific items.

**Comment by DavidPoliakoff** [comment]
In this instance, a solution like we did in #457 is probably in order, somewhere in a header file if __CUDA_ARCH__ isn't large enough we error with "Please set __CUDA_ARCH__" rather than leaving the user to confusion

**Comment by rhornung67** [comment]
@davidbeckingsale and @MrBurmark I believe this issue is resolved with the cuda arch guards @MrBurmark added in the atomics and the stuff I added to the user guide a couple of releases ago. Can you please verify?

**Comment by MrBurmark** [comment]
Yes, I think this was fixed a while ago.
