### ISSUE TITLE
Fix "vanilla cmake" build system

### ISSUE THREAD

**Issue by ajkunen** [LLNL/RAJA#52]
Sorry if this comes off as blunt...

@rhornung67 and I were trying to get RAJA to build on BG/Q with no success.

I didn't review any of the vanilla cmake PR, but now that I'm looking at it.... well, it's worrisome.
Using host-config files was pretty rock solid, and using raw cmake seems terrible.

Now instead of baking in the compiler+architecture flags in a way that makes sense, using a host-config file, we have a compiler cmake module with a large switch-yard in it.  Is this really better?

My understanding was that if we used a tool like Spack, it would have been able to invoke cmake directly and bypass the host-config script.  This allowed us to either use the HC files or not.   But now we are forced into using an odd combination of shell scripts and cmake modules that take the place of the HC files.

I think this was a major regression, both on platform support and usability.

**Comment by DavidPoliakoff** [comment]
Think @davidbeckingsale is out, I'll give it a look. See https://github.com/LLNL/RAJA/issues/23 for why we initially wanted to move away from host-configs, it died in a confusing way for users not on an LC system. Spack is still of interest. I'm responding to your email now, but that's the short version

**Comment by davidbeckingsale** [comment]
I have a response on the way, and am currently building/running with both Clang and GCC on Vulcan.

**Comment by DavidPoliakoff** [comment]
Hey, is this still an open problem? If it is, should I be doing things to solve it?

**Comment by davidbeckingsale** [comment]
Rich and I have this under control. You are welcome to give the 'features/both-builds' branch a try if you are interested in seeing the changes.

**Comment by rhornung67** [comment]
@DavidPoliakoff and @davidbeckingsale I just pushed a minor change to quiet a clang compiler warning.  I think we're good for now (it will satisfy most folks, I believe) and the branch can be merged into develop. If you agree, we should do this soon since I updated the configuration and build section of the user docs and pushed those changes. Can one/both of you give them a quick read and let me know if you want me to change anything or if I missed something?  Thanks.

**Comment by davidbeckingsale** [comment]
Build docs look good to me.

Cheers,
--David

---
David Beckingsale, david@llnl.gov, people.llnl.gov/david <http://people.llnl.gov/david>
Center for Applied Scientific Computing @ Lawrence Livermore National Laboratory

**Comment by rhornung67** [comment]
Thanks. Merge away!

**Comment by davidbeckingsale** [comment]
Will merge after lunch, couple of conflicts to fix.

Cheers,
--David

---
David Beckingsale, david@llnl.gov, people.llnl.gov/david <http://people.llnl.gov/david>
Center for Applied Scientific Computing @ Lawrence Livermore National Laboratory

**Comment by rhornung67** [comment]
We’ve got an issue with icpc 16.0.109 on chaos. CMake is reporting an error and I don’t understand what the output log file is telling me.  Can you look at that?  Thanks.

**Comment by rhornung67** [comment]
@davidbeckingsale I've committed a coupld of fixes for icpc on chaos. However, We're getting some error out of CMake about not knowing how to set the C++11 compiler flags.  The code builds and runs

**Comment by davidbeckingsale** [comment]
Pinging @trws - what's the best way to deal with some compilers (Intel) not being handled by CMake's CXX_STANDARD stuff?

**Comment by trws** [comment]
Best? Use a newer version of cmake. The newest does support ICC for that stuff.

Realistic? Since we care about ICC, check the CMAKE_COMPILER_ID, and if it's ICC and the version is below <insert version that made that work here> add the known flag.  We'll probably want to do the same thing for XL and PGI.

Also, why closed?

**Comment by davidbeckingsale** [comment]
Closed because it got merged, before I realized Rich had noted this issue.
There was a "hot fix" that added the check you describe for Intel.

**Comment by trws** [comment]
Note: it is apparently possible to install icc/icpc on travis, we should talk to the Intel license folks about getting that done.  Also the BGQ cross-compiler if we can find a way.

**Comment by rhornung67** [comment]
Do we really need that? Wouldn't it be better to use Travis to launch builds and test on LC machines?

**Comment by keasler** [comment]
The joys of open-source dependencies.

-Jeff

**Comment by trws** [comment]
The other options are run the stuff on travis or have a secondary set of 
smoke-tests with bamboo.  I'm actually for having the second anyway, in 
principle, but having travis actually manage it all would be pretty 
nice...

**Comment by rhornung67** [comment]
Then, it’s probably best to use Bamboo to build and run our tests on LC machines. It’s straightforward to set up Bamboo plans to pull from github, etc.   Note that there are some other bizarre Bamboo issues we have discovered as we are standing this up for the CS Toolkit related to git submodules, etc. We are trying to resolve these with Atlassian admins….
