### ISSUE TITLE
Mistake in the user guide

### ISSUE THREAD

**Issue by bangerth** [LLNL/RAJA#535]
I don't know where the home of the sources of the user guide at https://media.readthedocs.org/pdf/raja/develop/raja.pdf are, or I would have fixed this myself. Either way, on p. 10, it introduces simple loops and has this code example:
```
RAJA::forall<exec_policy>(iter_space I, [=] (index_type i)) {
    c[i] = a[i] + b[i];
  });
```
This is not going to work if `c`, `a`, and `b` are plain arrays (because they can't be copied via `[=]`, but in any case, that's not what you want: Copying `c` into the lambda will then modify the copy, not the object that lives outside the lambda. I'm pretty sure you wanted to write this as `[](index_type i) { ... }` :-)

**Comment by DavidPoliakoff** [comment]
@bangerth , for the majority of our users, `c`, `a`, and `b` are pointers, that syntax copies the value of those pointers, but the underlying data is modified as you'd expect. Thanks for the feedback, we'll try to make that more clear for users going forward

**Comment by bangerth** [comment]
Oh, I see. It's true that then this works. I had expected that because you are writing C++ code, that you'd also want this to work for `std::vector` or similar. The solution is of course pretty simple -- just use `[](...)` or `[c,a,b](...)` and it will work for everything: whether it's a pointer or an actual object.

**Comment by rhornung67** [comment]
@bangerth, I guess the documentation could be clearer.  I will expand the code example you cited to include the types of the items captured in the lambda. In any event, you would not want whole arrays of data to be copied via lambda capture for each kernel as this would tank performance.
