### ISSUE TITLE
Document RAJA CMake config for external projects

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/RAJA#54]
We now have a CMake config file installed with RAJA, this can be used to easily include RAJA in external projects that also use a CMake build system.

**Comment by DavidPoliakoff** [comment]
Where should this live? http://software.llnl.gov/RAJA/config_build.html ?

**Comment by davidbeckingsale** [comment]
Maybe in a "Using RAJA" section? I know @rhornung67 is planning to add some primer documentation, so it would probably be] appropriate to link back to the documentation about the CMake file at the point in the primer we send people off to work on their own code.

**Comment by rhornung67** [comment]
Thanks.

**Comment by rhornung67** [comment]
@davidbeckingsale is this done?

**Comment by davidbeckingsale** [comment]
Nope. Shall I add it to the rc branch?

**Comment by rhornung67** [comment]
Sure. That's where I've been adding to the documentation.  Thanks.

**Comment by rhornung67** [comment]
@davidbeckingsale did this get added to the docs?

**Comment by davidbeckingsale** [comment]
Yup: https://raja.readthedocs.io/en/master/using_raja.html
