### ISSUE TITLE
blt_mpi_smoke test fails

### ISSUE THREAD

**Issue by doronbehar** [LLNL/RAJA#569]
With the latest release, and the following `cmake` configuration:

```
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON \
    -DENABLE_MPI=On \
    -DENABLE_CHAI=Off \
    -DENABLE_FT=On \
    -DENABLE_FRUIT=On \
    -DENABLE_OPENMP=On \
    -DENABLE_FORTRAN=On \
    -DENABLE_GMOCK=On \
    -DENABLE_TBB=On \
    -DRAJA_USE_FLOAT=On \
    -DRAJA_USE_COMPLEX=On \
```

`make check` fails:

```
96% tests passed, 1 tests failed out of 28

Total Test time (real) =   1.44 sec

The following tests FAILED:
          5 - blt_mpi_smoke (Failed)
Errors while running CTest
make: *** [Makefile:119: test] Error 8

```

**Comment by doronbehar** [comment]
From inspecting the cmake files, I can see `-DENABLE_MPI` affects only the [blt submodule](https://github.com/LLNL/blt). I'm not sure I understand what the MPI feature is for and what do you mean by saying that RAJA doesn't require it but I'll disable it for my build.

**Comment by davidbeckingsale** [comment]
Yup, that's right.

MPI is a library that is used for writing applications that use message passing for parallelism. RAJA doesn't use MPI, but blt provides support for it since lots of other applications that use blt depend on MPI.

**Comment by vmiheer** [comment]
@davidbeckingsale, is Raja not supporting mpi by design (it's made for optimizing single node) or in future, there is a plan to add mpi support?

**Comment by rhornung67** [comment]
@vmiheer RAJA is designed and intended to be used as an on-node portable programming abstraction.  Applications manage there own MPI usage.
