### ISSUE TITLE
Column Major Views

### ISSUE THREAD

**Issue by rcarson3** [LLNL/RAJA#585]
I'm currently working on an initial investigation of porting certain sections of my code-base to run on a GPU for an ECP project. A number of the data structures I'm dealing with are stored in column-major order. So, I was wondering if there was a simpler way of telling the view to stride along column-major order than the below example:

```C++
const int DIM1 = 2;
const int DIM2 = 2;
const int DIM3 = 3;
const int DIM = 3;

double *data = new double[DIM1 * DIM2 * DIM3];

//Extra lines needed to have the unit strides along the left most dimension.
std::array< RAJA::idx_t, DIM> perm {{2, 1, 0}};
RAJA::Layout<DIM> layout = RAJA::make_permuted_layout( {{DIM1, DIM2, DIM3}}, perm );
//Now I can get a view
RAJA::View<double, RAJA::Layout<DIM, RAJA::Index_type, 0> > data_view(data, layout);
```

Now, I probably won't have too many cases where I won't be able to reuse the layout created. However, I was wondering if there was a similar version to the row-major version of Views where I could pretty much do something like the below but just tell ```RAJA::View``` that my data is in column-major order.

```C++
RAJA::View<double, RAJA::Layout<DIM> > data_view(data, DIM1, DIM2, DIM3);
```

**Comment by rhornung67** [comment]
@rcarson3 The default striding order for a RAJA View with the default layout (your very last line above) is right-most index is stride 1, next right-most index has stride equal to the extent of the right-most dimension, etc. See https://raja.readthedocs.io/en/v0.7.0/feature/view.html for a detailed description of RAJA Views and Layouts. Our default is the same as the striding order for a multi-dimensional array in C++/C (you need to pick a default and this seems the most reasonable to us). The way you permute the strides with the permuted layout in your example above is how you get what you want with the way we designed the RAJA API. 

@ajkunen or @artv3 do you have any thoughts to add?

**Comment by rcarson3** [comment]
@rhornung67 thanks for the answer, and it sounds like I wasn't missing anything when I was reading over the documents. I just wanted to make sure there wasn't a flag/option I could add to the ```RAJA::View``` instantiation that would help remove some additional lines of code. Since, I would say column-major/Fortran style of memory layout for arrays is another fairly common way of representing multi-dimensional arrays.

**Comment by rhornung67** [comment]
No problem. You even got the optimization of indicating in the Layout template parameters to specify the stride-1 index dimension. This saves some arithmetic operations in the multi-dimensional index calculations. 

Typically, we hide the definition of Layout and View types in header files and use aliases to access them in the code. If it's easier and makes your code more readable, you could make 'RowMajorView' and 'ColumnMajorView' aliases. 

Please let us know if you have any other questions or suggestion.  Thanks.

**Comment by rcarson3** [comment]
I hadn't thought of doing something like using aliases to simplify things for this. I'll probably try experimenting with some of this to see what works best.
