### ISSUE TITLE
Test failures with CUDA-enabled RAJA

### ISSUE THREAD

**Issue by minitu** [LLNL/RAJA#600]
Hi,

I'm getting a lot of test failures with the CUDA-enabled build of RAJA, and was wondering if this is normal.

```
9% tests passed, 32 tests failed out of 35

Total Test time (real) =   0.75 sec

The following tests FAILED:
          1 - blt_gtest_smoke (Failed)
          5 - camp_tuple.exe (Failed)
          6 - test-atomic.exe (Failed)
          7 - test-region.exe (Failed)
          8 - test-layout.exe (Failed)
          9 - test-view.exe (Failed)
         10 - test-timer.exe (Failed)
         11 - test-integral-limits.exe (Failed)
         12 - test-rajavec.exe (Failed)
         13 - test-iterators.exe (Failed)
         14 - test-indexvalue.exe (Failed)
         15 - test-span.exe (Failed)
         16 - test-kernel.exe (Failed)
         17 - test-multipolicy.exe (Failed)
         18 - test-simd.exe (Failed)
         19 - test-sharedmem.exe (Failed)
         20 - test-reduce.exe (Failed)
         21 - test-forall.exe (Failed)
         22 - test-indexset.exe (Failed)
         23 - test-segments.exe (Failed)
         24 - test-scan.exe (Failed)
         25 - test-reductions.exe (Failed)
         26 - test-forall-view.exe (Failed)
         27 - test-synchronize.exe (Failed)
         28 - test-cuda-scan.exe (Failed)
         29 - test-cuda-reduce-sum.exe (Failed)
         30 - test-cuda-reduce-min.exe (Failed)
         31 - test-cuda-reduce-loc.exe (Failed)
         32 - test-cuda-reduce-max.exe (Failed)
         33 - test-cuda-forall.exe (Failed)
         34 - test-cuda-forall-view.exe (Failed)
         35 - test-cuda-synchronize.exe (Failed)
```

I'm using the v0.8.0 release, and the commands used to build and test RAJA are the following:
```
mkdir build
cd build
cmake -DENABLE_CUDA=On ../
make -j
make test
```

**Comment by davidbeckingsale** [comment]
Does `make -j` succeed? And are you running `make test` somewhere that has an NVIDIA GPU accessible?

**Comment by minitu** [comment]
@davidbeckingsale `make -j` completes without any errors, and this was done on a GPU node of PSC Bridges that has 2 Tesla P100 GPUs.

**Comment by davidbeckingsale** [comment]
If you run `ctest -V`, you should be able to see see the test output. Can you post some of it here?

**Comment by minitu** [comment]
All of the errors seem to be from not being able to find some GLIBCXX version.
I've attached the entire output below.

[ctest_errors.txt](https://github.com/LLNL/RAJA/files/3082188/ctest_errors.txt)

**Comment by davidbeckingsale** [comment]
Okay, this normally happens if the system GCC compiler version is too old. Did you have to `module load` a newer compiler when you built RAJA? If so, make sure that same module is still loaded when you are running the tests.

What compiler did you use? And what's the version of the system default GCC compiler?

**Comment by minitu** [comment]
That's strange, because I'm using GCC 7.3.0 with `module load gcc/7.3.0`, which should be fairly new (it was loaded for the entire build and test process).
The most up-to-date version I can load is GCC 8.2.0, and the system default (without any modules) is GCC 4.8.5.

**Comment by davidbeckingsale** [comment]
I'm not sure your exact system configuration, but you could try including the lib directory of the GCC 7.3.0 compiler in your `LD_LIBRARY_PATH`. 

Let me know if that works.

**Comment by minitu** [comment]
That actually made all the tests pass!
Looks like some other modules that were loaded corrupted `LD_LIBRARY_PATH`, the GCC libraries were somehow removed from it.
Thank you so much for your help.

**Comment by davidbeckingsale** [comment]
No problems, glad we got it sorted! Please let us know if you have any other problems.
