### ISSUE TITLE
fixed threads per block (1024) in kernel causing failures on Turing Titan RTX

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#608]
In some cases, kernel will fall back or explicitly 1024 threads per block, which is not always possible to provide.

More importantly perhaps, while reducing the number fixes many problems, it breaks the tiling implementation if the number of threads per block drops below the tile sizes with no static_assert or runtime catch, just wrong results.  We probably need to figure out a way to make this safer, either always getting a runnable number or at least some static checks.

**Comment by MrBurmark** [comment]
I believe this issue is resolved.
The error checking and error messages can be improved, but now launch_bounds are being applied.

**Comment by trws** [comment]
Works for me.
