### ISSUE TITLE
Figuring out number of CUDA thread blocks (grid size)

### ISSUE THREAD

**Issue by minitu** [LLNL/RAJA#619]
Dear RAJA developers,

I am trying to find out the grid size for a RAJA kernel, that is part of an existing application (SW4lite).
I know that the block size is specified in the execution policy (e.g. `RAJA::cuda_exec<256>`), and I believe the grid size is somehow computed by RAJA at runtime.
Could you point me to the code where this calculation is done, so that I can just have RAJA print it out?
I would like to avoid having to manually go through the code if possible.

**Comment by MrBurmark** [comment]
https://github.com/LLNL/RAJA/blob/develop/include/RAJA/policy/cuda/MemUtils_CUDA.hpp#L210

**Comment by minitu** [comment]
Thanks, I was able to backtrack from there and it looks like the calculation for grid size is done in the `calculateDimensions` function.
