### ISSUE TITLE
Raja.hpp

### ISSUE THREAD

**Issue by Tdub1229** [LLNL/RAJA#632]
~/raja/examples$ mpicc wave-eqn.cpp 
In file included from wave-eqn.cpp:11:0:
memoryManager.hpp:11:10: fatal error: RAJA/RAJA.hpp: No such file or directory
 #include "RAJA/RAJA.hpp"
          ^~~~~~~~~~~~~~~
compilation terminated.

Not sure what a solution might be... I've checked the path and links.... They seem right

**Comment by davidbeckingsale** [comment]
You need to add the path to the installed RAJA headers and the library, e.g.:

`mpicc -I/path/to/RAJA/include -L/path/to/RAJA/lib -lRAJA wave-eqn.cpp`
