### ISSUE TITLE
Non-blockstride kernel policies for cuda

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJA#660]
Add a non-block striding kernel policies for cuda.
That is add a cuda_block_xyz_direct in addition to cuda_block_xyz_loop that maps directly to blocks instead of looping to do all work. This should reduce register pressure and allow the device block scheduler to dynamically schedule blocks for load imbalanced kernels.
This will break the ability to do things like grid synchronizes or grid scans, but we can add a cudaCooperativeKernel statement that maintains the current behavior while still allowing static policy sanity checks in the future.

**Comment by artv3** [comment]
I can take a swing at this.

**Comment by rhornung67** [comment]
@artv3 Thanks!

**Comment by artv3** [comment]
Resolved in v0.10
