### ISSUE TITLE
Documentation for cuda_block_x/y/z_loop policy

### ISSUE THREAD

**Issue by steveg21** [LLNL/RAJA#674]
In docs/sphinx/user_guide/feature/policies.rst, it would be very useful to further explain the behavior of cuda_thread_x/y/z_loop when used with cuda_block_x/y/z_loop.  For example, what happens when all available x thread blocks are exhausted?

There is some mention of this in the Matrix Multiplication example (docs/sphinx/user_guide/tutorial/matrix_multiply.rst), so a cross-reference would also be helpful.

**Comment by rhornung67** [comment]
@steveg21 not sure what you're asking here. What does it mean to exhaust all thread blocks? Do you mean all threads in a block? The cuda_thread_x/y/z_loop policies will apply a block-stride and reuse threads in a block if necessary.

**Comment by steveg21** [comment]
Yes, that is what I meant.  Adding "cuda_thread_x/y/z_loop policies will apply a block-stride and reuse threads in a block if necessary" would be useful.

**Comment by rhornung67** [comment]
OK. Thanks for clarifying. I will change the policy docs to be more descriptive either tomorrow and Friday. When I do, I will ask you to take a look and see if it makes sense to you.

**Comment by rhornung67** [comment]
@steveg21 please look over the CUDA execution policy descriptions in the following PR and let me know if you still find this unclear. Thanks.

https://github.com/LLNL/RAJA/pull/680

**Comment by rhornung67** [comment]
Modified user docs to user's satisfaction.
