### ISSUE TITLE
Windows VS 2019 build issues

### ISSUE THREAD

**Issue by thejonwong** [LLNL/RAJA#675]
After using cmake to generate visual studio project files not much seems to build successfully. Are there windows specific instructions somewhere? The blt_cuda_* tests seem to run, but nothing RAJA related.

**Comment by davidbeckingsale** [comment]
Hey @thejonwong - we use `cmake --build` to compile the project with VS 2017 in our continuous integration tests: https://github.com/LLNL/RAJA/blob/develop/appveyor.yml

Let me take a look locally and see if I can get it to build in Visual Studio directly.

**Comment by thejonwong** [comment]
@davidbeckingsale I tried:
mkdir build
cd build
cmake ..
cd ..
cmake --build build

I get many errors. This first is:
<source>\RAJA\include\RAJA/util/align.hpp(37,68): warning C4146: unary minus operator applied to
 unsigned type, result still unsigned [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(719,33): warning C4244: 'return': conversion from
'T' to 'int', possible loss of data [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(719,33): warning C4244:         with [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(719,33): warning C4244:         [ [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(719,33): warning C4244:             T=RAJA::Index_
type [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(719,33): warning C4244:         ] [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(724,33): warning C4244: 'return': conversion from
'const T' to 'int', possible loss of data [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(724,33): warning C4244:         with [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(724,33): warning C4244:         [ [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(724,33): warning C4244:             T=RAJA::Index_
type [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/index/IndexSet.hpp(724,33): warning C4244:         ] [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/util/StaticLayout.hpp(199,5): fatal error C1001: An internal error ha
s occurred in the compiler. [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/util/StaticLayout.hpp(199,5): fatal error C1001: (compiler file 'd:\a
gent\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\template.cpp', line 18673) [<source>\RAJA\buil
d\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/util/StaticLayout.hpp(199,5): fatal error C1001:  To work around this
 problem, try simplifying or changing the program near the locations listed above. [<source>\RAJ
A\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/util/StaticLayout.hpp(199,5): fatal error C1001: Please choose the Te
chnical Support command on the Visual C++ [<source>\RAJA\build\test\unit\cpu\bis.vcxproj]
<source>\RAJA\include\RAJA/util/StaticLayout.hpp(199,5): fatal error C1001:  Help menu, or open
the Technical Support help file for more information [<source>\RAJA\build\test\unit\cpu\bis.vcxp
roj]

**Comment by davidbeckingsale** [comment]
Thank you for the extra info. Are you able to try with a newer VS version?

**Comment by thejonwong** [comment]
Sorry. I just realized I'm actually using VS 2019. Changed title to reflect that.

**Comment by thejonwong** [comment]
@davidbeckingsale It seems that the test you reference only tests OpenMP on Windows. I got RAJA running with OpenMP with VS 2017 but not VS 2019. When I turned on the CUDA option I got the following error with VS 2017.

RAJA\include\RAJA/util/basic_mempool.hpp(364): error : namespace "std" has no member "max" [RAJA\build\RAJA.vcxproj]

Does the CUDA option work on windows?

**Comment by davidbeckingsale** [comment]
It _should_, but obviously that doesn't mean it will... We don't have any developers using CUDA with Windows, but we should have some people using this configuration. Let me look into it.

**Comment by thejonwong** [comment]
Thanks. I modified include/RAJA/util/basic_mempool.hpp by adding 
`#include <algorithm>`

That seems to allow things to compile nicely with CUDA. The smoke test runs but I get the following error when I run some of the cuda examples (below). Is there a required sm architecture? This particular windows machine has an older card that is only sm3.0 compatible but I've installed CUDA 10. I believe it's the GK107 chipset.

Any idea what this means?

```
PS \RAJA\build\bin\Debug> .\pi-reduce_vs_atomic.exe
RAJA pi example...

 Running C-style sequential pi approximation...
        pi = 3.141592653591073

 Running RAJA sequential pi approximation (reduction)...
        pi = 3.141592653591073

 Running RAJA sequential pi approximation (atomic)...
        pi = 3.141592653591073

 Running RAJA CUDA pi approximation (reduction)...
CUDAassert: no kernel image is available for execution on the device \RAJA\include\RAJA/policy/cuda/MemUtils_CUDA.hpp 210
```

**Comment by rhornung67** [comment]
RAJA requires a minimum CUDA architecture level of sm_35. 
See https://raja.readthedocs.io/en/master/config_options.html

You can select the architecture level using the CMake variable CUDA_ARCH. If it is not specified, sm_35 is selected by default if CUDA is enabled. I believe what your runtime error means that no GPU executable code is being generated.  @davidbeckingsale is that correct?

**Comment by thejonwong** [comment]
Thanks @rhornung67. Just to clarify does this mean RAJA tests won't be built at all for sm_30 or does it mean only tests that use atomics won't be supported for anything lower than sm_35? I interpreted the docs to mean the latter.
