### ISSUE TITLE
plugin pre/post get emitted twice

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#691]
In investigating some possible region merging opportunities in clang, Johannes found that the only thing currently inhibiting some of his clang optimizations from merging parallel regions under raja (in simple cases) is the pre/post hooks. More peculiarly, the pre and post hooks are getting emitted *twice* before and after each call, as in:

```
       run_all_pre_hooks();
       run_all_pre_hooks();
       execute_user_kernel_1();
       run_all_post_hooks();
       run_all_post_hooks();
       run_all_pre_hooks();
       run_all_pre_hooks();
       execute_user_kernel_2();
       run_all_post_hooks();
       run_all_post_hooks();
```

This seems peculiar enough to be worth looking into, it's for a super-basic pair of foralls (plain omp-parallel-for-exec foralls even).

**Comment by davidbeckingsale** [comment]
Reckon it's this? https://github.com/LLNL/RAJA/blob/develop/include/RAJA/pattern/forall.hpp#L460

Should it call `wrap::forall` internally?

**Comment by trws** [comment]
Yeah, that's probably it.  I would think either call wrap::forall from each outer one, or if possible it might be good to consolidate all of those pre/post invocations *into* wrap::forall.  IIRC every forall calls through there exactly once right?

**Comment by davidbeckingsale** [comment]
Yes, that's the idea, one non-wrap forall shouldn't ever call another. Can you ask Johannes to give that modification a try if he has something set up already?

**Comment by ajkunen** [comment]
I think it would be great to have some unit tests that check the number of times we call the hooks... I feel that this kind of thing has had regressions in the past

**Comment by davidbeckingsale** [comment]
@ajkunen  - see #693

**Comment by ajkunen** [comment]
@davidbeckingsale it's like you read my mind, and time traveled

**Comment by rhornung67** [comment]
@ajkunen haven't you left the country yet?
