### ISSUE TITLE
Layout 2 is identical to layout 1 in "Batched Matrix-Multiply (Permuted Layouts)"

### ISSUE THREAD

**Issue by twhite-cray** [LLNL/RAJA#709]
The code for layout 2 is identical to the code for layout 1 in "RAJA/docs/sphinx/user_guide/tutorial/permuted-layout.rst". According to the text, it should have a different `perm` value of `{{1,2,0}}`, along with different `View` variable names.

**Comment by rhornung67** [comment]
@twhite-cray thanks for pointing this out. I will fix it soon.

**Comment by rhornung67** [comment]
Fix is merged into the develop branch. It appears in that version of the user docs on RTD.
