### ISSUE TITLE
BoundsCheck incorrectly using `0 < idx` in Layout.hpp?

### ISSUE THREAD

**Issue by twhite-cray** [LLNL/RAJA#711]
I built Raja with `-DRAJA_ENABLE_BOUNDS_CHECK=On`, and my test program is getting many copies of the following error message.

`Error at index 0, value 0 is not within bounds [0, 2]`

It looks like it comes from line 189 of `RAJA/include/RAJA/util/Layout.hpp`, in function `BoundsCheck`.

`    if(!(0<idx && idx < sizes[N])) BoundsCheckError<N>(idx);`

Shouldn't the first comparison be `0<=idx`?

If so, I think line 178 needs the same change.

`    RAJA_ASSERT(0 < idx && idx < (sizes[N]) && "Layout index out of bounds \n");`

**Comment by rhornung67** [comment]
@artv3 please fix this issue as soon as you have a chance. Thanks.

**Comment by artv3** [comment]
Thanks @twhite-cray! Just set up a bugfix PR.

**Comment by twhite-cray** [comment]
Thanks for the quick fix!
