### ISSUE TITLE
Missing `-Xcompiler` flag when CUDA and OpenMP are enabled in CMake configuration

### ISSUE THREAD

**Issue by pelesh** [LLNL/RAJA#731]
Perhaps I am doing something wrong, but when building RAJA with `ENABLE_CUDA` and `ENABLE_OPENMP` set to `ON`, the build fails with message
```
nvcc fatal   : Unknown option 'fopenmp'
```
If I enable CUDA or OpenMP alone everything works fine. 

I found that there is a missing `-Xcompiler` flag in front of `-fomp`. If I insert it manually, the compilation continues fine. I couldn't find the place in CMake files where I could fix this. I tried editing `SetupPackages.cmake`, but that didn't seem to have effect. 

The complete compilation line configured by CMake looks like this:
```
$ make VERBOSE=1
...
[  0%] Building CUDA object CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o
/.../cuda/10.1/bin/nvcc -ccbin=/.../gcc/7.4.0/bin/g++  -I/.../cuda/10.1/include -I/.../src/raja/raja/include -I/.../src/raja/build/include -I/.../src/raja/raja/tpl/cub -I/.../src/raja/raja/tpl/camp/include  -restrict -arch sm_35 --expt-extended-lambda --expt-relaxed-constexpr -O2 -Xcompiler=-fPIC   -fopenmp -std=c++11 -x cu -c /.../src/raja/raja/src/AlignedRangeIndexSetBuilders.cpp -o CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o
nvcc fatal   : Unknown option 'fopenmp'
...
```

## Build Info

**RAJA version**: 0.10.1, master
**System**: Power9/V100
**C/C++**: gcc 7.4.0
**CUDA**: 10.1.105
**CMake**: 3.13.4

**Comment by rhornung67** [comment]
@pelesh if you enable CUDA and OpenMP, you have to pass '-Xcompiler -fopenmp' (or similar flag) in the variable 'CMAKE_CUDA_FLAGS_<release type> so that nvcc passes it along to the host compiler.

As an example, look at the build script 

RAJA/scripts/lc-builds/blueos_nvcc10_gcc7.3.1.sh

and the Cmake cache file it pulls in (the '-C' option).

**Comment by pelesh** [comment]
@rhornung67 I tried that, but the problem is with `-fopen` flag that CMake adds when I enable OpenMP backend in RAJA. This one is not prepended with `-Xcompiler`. 

Nevertheless, I figured out how to reproduce this bug and found a simple workaround.

The issue occurs if I configure RAJA with defaults (including `ENABLE_OPENMP=ON`), and then try to modify RAJA build configuration to add CUDA support. For example:
```
$ cmake ../raja
$ cmake -DENABLE_CUDA="ON" ../raja
$ make
[  0%] Building CUDA object CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o
nvcc fatal   : Unknown option 'fopenmp'
```
The workaround I found is to nuke the existing build configuration and start from scratch with CUDA enabled:
```
$ cmake ../raja
$ rm -Rf ./*
$ cmake -DENABLE_CUDA="ON" ../raja
$ make
   (build completes successfully)
```

**Comment by davidbeckingsale** [comment]
@pelesh - unfortunately, some values in the build configuration get set up the first time CMake is run, and do not get regenerated if you change options and run CMake again. As you've found out, the only workaround here is to start with a fresh build.
