### ISSUE TITLE
Build issues related to clone recursive and older versions of RAJA

### ISSUE THREAD

**Issue by rcarson3** [LLNL/RAJA#733]
One of my libraries currently makes use of the Raja v0.9.0 release. It was brought to my attention recently that if you use the ```git clone https://github.com/LLNL/RAJA.git --recursive``` and then checking out the v0.9.0 branch that during the build of RAJA it fails when attempting to compile the ```test/unit/test-kernel-lambda-args.cpp``` file. Previously I had not run into this issue, and in fact I had done this as recently as last week. If you instead simply just do ```git clone https://github.com/LLNL/RAJA.git --branch v0.9.0 --single-branch``` and then run ```git submodule init``` and ```git submodule update``` everything compiles and the tests all pass as expected. It appears to me that the issue might be in one of the submodules either within ```BLT``` or ```GTests```.

Now I really wouldn't say this is a pressing issue for me at least, since I've found a workaround that works. However, I figured I'd bring it up in case other users run into the same issue and provide them with at least one workaround to the problem.

**Comment by rhornung67** [comment]
@rcarson3 I plan to do a new release on Wed (1/29), which should address the issue you reported. Thanks for pointing it out.

**Comment by davidbeckingsale** [comment]
@rcarson3 - do you run `git submodule update` after checking out the v0.9.0 branch? When you clone, you are getting the `develop` branch, which has different submodule versions to 0.9.0

**Comment by rcarson3** [comment]
@davidbeckingsale I had not been nor had my other teammate. We both realized our mistake yesterday after I told him about my workaround, and he added the ```git submodule update``` into our original build script which got things working again. I'm going to go ahead and close this issue, since it was an error on our part of forgetting to add the ```git submodule update``` after checking out the v0.9.0 branch.

**Comment by davidbeckingsale** [comment]
No problems, please let us know if you have any other questions.
