### ISSUE TITLE
Review CUDA unit tests

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#751]
After we merge the reorganization of the unit tests into develop (awaiting PR review), someone needs to go through the tests in the cuda subdirectory and merge them into the new unit test structure to avoid redundant test code and make them consistent with the rest of the tests.

**Comment by mdavis36** [comment]
@rhornung67 I can take this one.

**Comment by rhornung67** [comment]
Thanks @mdavis36. Is it clear what I'm looking for?  My hope is that after we're done with the unit tests and functional tests there will be no PM-specific test subdirectories. For PM-specific unit tests, we should be able to parameterize them so the same test code is used by all back-ends.

**Comment by rhornung67** [comment]
Only sync test remains. This is captured in a more recent issue.
