### ISSUE TITLE
Segfault with scan of empty array

### ISSUE THREAD

**Issue by mclarsen** [LLNL/RAJA#768]
For reasons, I tried a scan of an array of size 0 and I got a segfault. I don't know if you consider this an issue or not, but I thought I would mention it.

**Comment by ajkunen** [comment]
@mclarsen that's a bug.  We should check for size 0 and do a NOP

**Comment by mclarsen** [comment]
I'm trying to track down if I didn't do something silly like hand it a bad pointer.

**Comment by mclarsen** [comment]
```2 libdray.dylib`dray::detail::compact_partials(dray::Array<dray::VolumePartial> const&) [inlined] std::__1::enable_if<all_of<RAJA::type_traits::is_sequential_policy<RAJA::policy::sequential::seq_exec> >::value, void>::type RAJA::impl::scan::exclusive<RAJA::policy::sequential::seq_exec, int*, int*, RAJA::operators::safe_plus<int, int>, int>(begin=0x0000000000000000, out=0x0000000000000000, v=0)```

**Comment by mclarsen** [comment]
I think I did

**Comment by rhornung67** [comment]
@mclarsen thanks for point this out. I think we should be able to catch some incorrect usage, but not all.
