### ISSUE TITLE
Version number in documentation is out-of-date

### ISSUE THREAD

**Issue by jturner314** [LLNL/RAJA#770]
I was just passing by, and noticed that the [version number in the Sphinx documentation](https://github.com/LLNL/RAJA/blob/1417acaf196b3c9db57cbceec60f0c3c57f6967b/docs/sphinx/user_guide/conf.py#L68-L71) is out-of-date. This version number appears in the title of the web browser when browsing the docs.

**Comment by rhornung67** [comment]
@jturner314 thanks for bringing this up. I new this was an issue and I neglected to address it.  It will be fixed in future releases.

**Comment by rhornung67** [comment]
Fixed in code. Fix will appear in v0.12.0 release
