### ISSUE TITLE
XL compiler failing to build with errors in real_datatypes.hxx

### ISSUE THREAD

**Issue by tomdeakin** [LLNL/RAJA#79]
When building RAJA code with the XL compiler targeting Power 8, the following error occurs in `real_datatypes.hxx`

```
error: unknown linkage language "builtin"
```

This happens when it gets to building LULESH, or if you skip building these, on your own code. RAJA itself builds OK.

A possible fix is to comment out, as below:

```
#elif defined(RAJA_COMPILER_XLC12)
/*
#ifndef RAJA_COMPILER_XLC_POWER8
extern
#ifdef __cplusplus
"builtin"
#endif
void __alignx(int n, const void* adds);
#endif
*/
```

**Comment by davidbeckingsale** [comment]
@rhornung67 can this bit of code be removed?

**Comment by rhornung67** [comment]
@davidbeckingsale Probably. I don't think we are using the __alignx stuff -- and it was experimental at one point.  I say excise it and we can add it, or something else, if we need to in the future.

**Comment by tomdeakin** [comment]
It looks like if the `RAJA_COMPILER_XLC_POWER8` is defined the offending code (the builtin stuff) won't be compiled in. Is there a canonical way of defining these things in your CMake system?

**Comment by davidbeckingsale** [comment]
You could define that rather than just `RAJA_COMPILER_XLC` as you have done in #80 

As @rhornung67 said, I think this is unused anyway and can probably be removed.
