### ISSUE TITLE
Developing Performance-Monitoring Plugins for RAJA

### ISSUE THREAD

**Issue by JohnHynes** [LLNL/RAJA#828]
**Developing Performance-Monitoring Plugins for RAJA**
The RAJA performance portability layer is a C++ abstraction that allows developers to write
single source computational kernels that can be dispatched to various programming model
backends including OpenMP and CUDA. RAJA includes a plugin infrastructure that allows
external code to be executed before and after each loop kernel. This infrastructure allows us to
develop tools that can help users analyze and debug application performance.

This project will develop new plugins and infrastructure to enable more tools to be connected
to RAJA. In particular, we will focus on connecting tools developed as part of the Kokkos Tools
suite to the RAJA plugin infrastructure. The Kokkos tools infrastructure defines a series of
function signatures that can be implemented by tools that can be loaded dynamically by the
application at runtime. This allows new tools to be connected to applications without
recompilation.

**Development Plan**
This project will require developing new software components for RAJA, as well as documenting
and testing the new code:
• Developing tests to ensure that the new components function correctly.
• Writing documentation and examples showing how new plugins can be developed and
connected to RAJA.
• Applying the developed code to applications to show how it can be used to help
developers understand application performance.

- [x] A mechanism for dynamically loading plugins at runtime.
- [x] Code that will call the appropriate functions of the Kokkos tools from the RAJA plugin
calls.
- [x] Developing tests to ensure that the new components function correctly.
- [x] Applying the developed code to applications to show how it can be used to help
developers understand application performance.

**Links**
• RAJA: https://github.com/LLNL/RAJA
• RAJA Plugin API: https://github.com/LLNL/RAJA/blob/develop/include/RAJA/util/PluginStrategy.hpp
• Kokkos Tools: https://github.com/kokkos/kokkos-tools

**Comment by DavidPoliakoff** [comment]
Hey @JohnHynes, don't hesitate to get in touch if any of the interface is confusing or poorly documented. Some relevant facts:

1) The header files in which Kokkos defines types for use in the interface are entirely self-contained, and don't require anything from Kokkos, those are https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Profiling_C_Interface.h and https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Profiling_Interface.hpp
2) The Kokkos-side implementation that implements the dlsym and invocation of these guys is located here https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Profiling.hpp

Obviously the files in 2 are a little Kokkos-centric, but probably wouldn't take much effort to port over. Anyway, in addition to GitHub I'm on your Slack or email if you need anything
