### ISSUE TITLE
BG/Q timer output issues

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#84]
Bad timer output running RAJA version of LULESH-v1.0 with OpenMP on BG/Q. I'm running the code in @trws branch trws:chrono-timer-fix.

Here's what I see when compiled with gcc-4.8.4:

"chrono" option (BAD)
Total Cycle Time (sec) = -100876817.742690
Total main Time (sec) = 1351950087.947958

"gettime" option (BAD)
Total Cycle Time (sec) = -127775258991.775274
Total main Time (sec) = 127775260511.756386

Here's what I see with with clang-3.9.0:

"chrono" option (GOOD)
Total Cycle Time (sec) = 79.276949
Total main Time (sec) = 79.339523

"gettime" option (BAD)
Total Cycle Time (sec) = 20221439.999974
Total main Time (sec) = -9688.000000

I believe the output is good with either timer option when running with gcc compilation on LLNL Linux clusters.

**Comment by trws** [comment]
This is going to require more digging than I had initially hoped.  I see the same issue with lulesh, but not with a smaller test using the same timer.  There must be something going on that causes the monotonic clock to not behave, but I'm not sure what a good solution to that is.  We could switch to using the system_clock on BGQ, but that comes with its own drawbacks.

**Comment by rhornung67** [comment]
The timers have always been froggy on BG/Q.  For example, using the C standard library clock gives the correct timing for a code run with multiple OpenMP threadsm which is not really correct. On our Intel machines, using clock gives an aggregate time summed over all threads, which is expected.  Go figure...

**Comment by trws** [comment]
Your added gettime information might be the telling factor here.  The gettime version is using CLOCK_MONOTONIC, which is the same thing steady_clock is implemented with in the C++ standard library on this platform.  Maybe we just can't use monotonic on BGQ.  It should be pretty easy to special-case that as long as we can detect that we're compiling on that system.

**Comment by ajkunen** [comment]
This has been a perpetual problem with Kripke on BG/Q.... To my knowledge there really is no "portable" timer that we can use.  We probably need to just accept that timing information is platform specific.

**Comment by trws** [comment]
The output I'm getting from steady_clock on BG/Q is actually a serious error, that clock can't ever go backwards, so getting negative anything is breaking C++ compliance just by itself.  It should be portable, but if we're stuck with a broken libstdc++, maybe that means we should use libc++ by default on BG/Q?  It certainly seems to do it right.

**Comment by trws** [comment]
So, I'm finding posts around the internet that say BG/Q has no support for monotonic clocks on its compute nodes.  This is a BG/Q specific issue, but should be fixed by switching clocks.
