### ISSUE TITLE
Clarify RAJA CMake variable names.

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#850]
All CMake variables used in the RAJA build system that are specific to CMake should have the 'RAJA_' prefix to distinguish from BLT or CMake variables.

**Comment by mlohry** [comment]
@rhornung67 , maybe unrelated to this issue but I was looking here for answers re cmake behavior.

In my existing project, using `find_package(RAJA REQUIRED)` and pointing at it my installed location with `RAJA.cmake`, `cmake -DRAJA_DIR=$HOME/usr/local/share/raja/cmake/` in my case, it seems to "find" raja okay but it never defines any cmake variables. e.g. I'm expecting to see a `${RAJA_INCLUDE_DIR}` and `${RAJA_LIBRARY_PATH}$` defined, but there's nothing.

What's the expected behavior here?

**Comment by davidbeckingsale** [comment]
Hey @mlohry, you should be able to use the `RAJA` cmake target, which you can depend on to get things like the includes, libraries. If your project also uses BLT, then the CUDA/HIP dependencies will also be correctly found.

**Comment by mlohry** [comment]
@davidbeckingsale , so explicitly add a `include(${RAJA_DIR}/raja-config.cmake)` to my cmake in addition to the `find_package(RAJA)`?

**Comment by davidbeckingsale** [comment]
Nope, `find_package(RAJA)` should do that, and it will load all the exported targets.

**Comment by mlohry** [comment]
@davidbeckingsale , example from a totally barebones cmake file,

```
cmake_minimum_required(VERSION 3.2.2)
project(dummy)

find_package(RAJA REQUIRED)

get_cmake_property(_variableNames VARIABLES)
list (SORT _variableNames)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
```

where I'm just printing out all the variables in scope, when i run `cmake ../ -DRAJA_DIR=${HOME}/usr/local/share/raja/cmake | grep -i raja` the output I see is 

```
-- CMAKE_BINARY_DIR=/home/mlohry/tmp/buildrajatmp/build
-- CMAKE_CACHEFILE_DIR=/home/mlohry/tmp/buildrajatmp/build
-- CMAKE_CURRENT_BINARY_DIR=/home/mlohry/tmp/buildrajatmp/build
-- CMAKE_CURRENT_LIST_DIR=/home/mlohry/tmp/buildrajatmp
-- CMAKE_CURRENT_LIST_FILE=/home/mlohry/tmp/buildrajatmp/CMakeLists.txt
-- CMAKE_CURRENT_SOURCE_DIR=/home/mlohry/tmp/buildrajatmp
-- CMAKE_HOME_DIRECTORY=/home/mlohry/tmp/buildrajatmp
-- CMAKE_PARENT_LIST_FILE=/home/mlohry/tmp/buildrajatmp/CMakeLists.txt
-- CMAKE_PLATFORM_INFO_DIR=/home/mlohry/tmp/buildrajatmp/build/CMakeFiles/3.16.3
-- CMAKE_SOURCE_DIR=/home/mlohry/tmp/buildrajatmp
-- CONFIG_FILES=/home/mlohry/usr/local/share/raja/cmake/RAJA-release.cmake
-- PROJECT_BINARY_DIR=/home/mlohry/tmp/buildrajatmp/build
-- PROJECT_SOURCE_DIR=/home/mlohry/tmp/buildrajatmp
-- RAJA_CONFIG=/home/mlohry/usr/local/share/raja/cmake/raja-config.cmake
-- RAJA_CONFIG_LOADED=TRUE
-- RAJA_CONSIDERED_CONFIGS=/home/mlohry/usr/local/share/raja/cmake/raja-config.cmake
-- RAJA_CONSIDERED_VERSIONS=unknown
-- RAJA_DIR=/home/mlohry/usr/local/share/raja/cmake
-- RAJA_FOUND=1
-- RAJA_VERSION_COUNT=0
-- RAJA_VERSION_MAJOR=0
-- RAJA_VERSION_MINOR=13
-- RAJA_VERSION_PATCH=0
-- RAJA_VERSION_PATCHLEVEL=0
-- RAJA_VERSION_TWEAK=0
-- _DIR=/home/mlohry/usr/local/share/raja/cmake
-- dummy_BINARY_DIR=/home/mlohry/tmp/buildrajatmp/build
-- dummy_SOURCE_DIR=/home/mlohry/tmp/buildrajatmp
-- Build files have been written to: /home/mlohry/tmp/buildrajatmp/build
```

no mention of include dir or library.

**Comment by davidbeckingsale** [comment]
It won't be variable, but a property of the actual RAJA target. If you add something like:
`get_target_property(_rajaIncludes RAJA INCLUDE_DIRECTORIES)`
and print it out you should see them.

**Comment by mlohry** [comment]
Ah okay, if I dump all the target properties I see it now, thanks.

**Comment by rhornung67** [comment]
@davidbeckingsale this issue can be closed, correct?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale this issue can be closed, correct?

Yup!

**Comment by rhornung67** [comment]
Done.
