### ISSUE TITLE
Remains of CHAI dependency?

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/RAJA#864]
I found ENABLE_CHAI in the CMakeLists.txt and the documentation.

Since it seems obsolete, so I suggest removing it. I can do it if this is confirmed.

**Comment by davidbeckingsale** [comment]
Yup, that's obsolete - we would be happy to receive a PR, thanks @adrienbernede

**Comment by rhornung67** [comment]
@adrienbernede I will make these fixes in the release candidate branch I am working on. Thanks for pointing it out.

**Comment by rhornung67** [comment]
@davidbeckingsale please check this user doc page for correctness: https://raja.readthedocs.io/en/v0.12.0-rc/plugins.html
Thanks.

**Comment by davidbeckingsale** [comment]
That page is up to date.

**Comment by rhornung67** [comment]
Thanks.  This also should be removed from the top-level CMakeLists.txt file, right @davidbeckingsale ?

if (ENABLE_CHAI)
  set (raja_depends
    ${raja_depends}
    chai)
endif ()

**Comment by rhornung67** [comment]
@adrienbernede I've taken care of this issue in the release candidate branch. So consider it done and I am closing the issue.
