### ISSUE TITLE
OpenMP-Target Reducer Interface Inconsistency

### ISSUE THREAD

**Issue by mdavis36** [LLNL/RAJA#898]
# Summary
It seems the omp-target Reduce_Data default constructors have been deleted. This appears to be inconsistent with other backends. A temporary fix was needed in `test-foall-segment-multiple-ReduceMin/Max/Sum.exe` to build correctly with omp-target enabled. The workaround can be seen in #894.

**Comment by rhornung67** [comment]
@mdavis36 can this issue be closed?
