### ISSUE TITLE
Add clang 10 compiler to Travis CI

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#909]
Add clang 10 docker image and enable clang 10 build/test on Travis with OpenMP target enabled with warnings as errors so we catch issues/potential issues. 

Aside: Do we need to keep Dockerfiles in the RAJA/travis-data/docker directory for old compilers that we don't test with anymore?

**Comment by trws** [comment]
Probably not, they’re really just there because we haven’t bothered 
to remove them.
