### ISSUE TITLE
Only require CUDA code to pass through nvcc (pass rest to host compiler)

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/RAJA#94]
When using CUDA, we require everything to be built with `nvcc`. Can we fix this up to only require GPU-enabled code to pass through nvcc, everything else using the host compiler directly?

**Comment by cbergstrom** [comment]
Are you certain you won't hit linking issues when doing this?

While it will not be a point that should be considered now, it is possible to compile CUDA code with clang as well as pathcu (PathScale CUDA driver). I think I'm saying, please don't hardcode nvcc and instead make it a variable which is uniformly defined.

**Comment by davidbeckingsale** [comment]
Mixing host and cuda compiled code works fine if you link it with the CUDA library (as you would expect).

This configuration won't likely be permanent, but the change in this issue is an improvement over the current state of things. I agree that making this configurable is a good idea - thanks for the comment :)

**Comment by keasler** [comment]
@cbergstrom Can you make a pathscale configuration?   We definitely don't want to trip up features like pathcu .

**Comment by cbergstrom** [comment]
@keasler Yeah I'll add it somewhere on my TODO list to make a pathscale configuration. My focus is honestly less on CUDA and more on OpenACC though.
