### ISSUE TITLE
target indexset-tests is not building under build-nvcc-7.5_gcc-4.9.3-release

### ISSUE THREAD

**Issue by jonesholger** [LLNL/RAJA#95]
I was tracking down a name clash with atomicAdd in CUDA8.0  when after I merged with develop notice some build failures.

**Comment by jonesholger** [comment]
Somewhere between https://github.com/LLNL/RAJA/commit/f765c05aefd8e34c06ddb2e011da25a68ba5ee9d and HEAD

**Comment by jonesholger** [comment]
ok tracked to https://github.com/LLNL/RAJA/commit/d26022c7ca1349a341cbbeaaf304f40ed3170d9c

**Comment by jonesholger** [comment]
Scanning dependencies of target indexset-tests
[ 69%] Building CXX object test/unit/cpu/CMakeFiles/indexset-tests.dir/test-indexsets.cxx.o
In file included from /g/g0/holger/workspace/raja_github/RAJA/test/unit/cpu/buildIndexSet.hxx:16:0,
                 from /g/g0/holger/workspace/raja_github/RAJA/test/unit/cpu/test-indexsets.cxx:3:
/g/g0/holger/workspace/raja_github/RAJA/include/RAJA/RAJA.hxx:75:31: error: stray ‘#’ in program
 #define RAJA_SUPPRESS_HD_WARN #pragma nv_exec_check_disable

@trws has a fix for this in PR87 -- this is a formatting bug that came back to bite us.

**Comment by jonesholger** [comment]
Ok, a bit further  - still errors when building target indexset-tests

**Comment by jonesholger** [comment]
Never mind waiting on PR93  - well that was fun ;)

**Comment by davidbeckingsale** [comment]
Fixed by #93
