### ISSUE TITLE
forall-atomic-multiview test will not link for OpenMP target back-end

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#973]
Building the test generates link errors due to undefined references to 'getenv', 'abort', etc. This may be due to a newer version of gtest being used.  Requires exploration and resolution.

**Comment by rchen20** [comment]
@rhornung67 Is this not linking for any of the OpenMPTarget compilers?

**Comment by rhornung67** [comment]
> @rhornung67 Is this not linking for any of the OpenMPTarget compilers?

Not for any of the XL compilers we have, IIRC. I tried vanilla clang also, but there are other issues that I've reported to our reps. Recent ibm-clang compilers also had issues.
