### ISSUE TITLE
CMake config assumes that CAMP is always the built-in version

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/RAJA#978]
Currently `RAJA-config.cmake` assumes that CAMP is the built-in version:

https://github.com/LLNL/RAJA/blob/705ec4d9a84a4f22d8757686b232cd027d682f71/share/raja/cmake/RAJA-config.cmake.in#L37

which fails when RAJA is built with an external camp (e.g., through Spack).  Expected behavior would be that the path to the external CAMP is recorded and used to populate `RAJA-config.cmake`.

The axom project does something similar to manage its RAJA dependency - it stores the path to RAJA in a variable called [RAJA_DIR](https://github.com/LLNL/axom/blob/develop/src/cmake/thirdparty/SetupAxomThirdParty.cmake#L51-L75) and uses that in the [config](https://github.com/LLNL/axom/blob/develop/src/cmake/axom-config.cmake.in#L94-L100).

Happy to contribute a PR but I think this requires repo access.

**Comment by rhornung67** [comment]
Merged into develop.
