### ISSUE TITLE
Document Gitlab CI process

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#983]
In the Developer Guide section of our sphinx docs, document the following:

- [x] Uberenv/spack generation of host-config files
- [ ] Process for managing/running Gitlab CI on PRs (smart resource usage, avoid excessive build/test runs when multiple PRs are in flight)
- [ ] Updating/modifying compiler specs (shared across RADIUSS projects)

**Comment by kab163** [comment]
I can help with this if need be :D

**Comment by rhornung67** [comment]
Great. I'm just about to put up a PR with the beginnings of this documentation. I'll add you as a reviewer.

**Comment by rhornung67** [comment]
Closing since GitLab CI organization and maintenance tasks are documented in the dev guide. We can add issues for individual items as needed.
