### ISSUE TITLE
Gitlab CI tasks

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJA#986]
Miscellaneous tasks to improve our Gitlab CI setup:

- [x] Update BLT so that we do not require a python environment for converting ctest output to junit, which Gitlab understands. Alternatively, add a gtest runtime option to each of our tests to generate junit out put.
- [x] Make uberenv a submodule.
- [x] Add more "date" commands to the CI script so we can track how long each phase takes.
- [x] Switch to using a service account, when enabled, to avoid sharing resources with other projects via a single user.
- [ ] Add RAJA Perf Suite to GItlab test pipeline.
- [ ] Add a "weekly" test pipeline that enables "exhaustive tests" and runs on the weekend. Note: resource allocation times will need to be bumped for these builds (not sure how to do that with our current specs setup, since we don't want to increase the times for regular builds)
- [x] Add a test pipeline for El Capitan EA platforms.
- [ ] Enable a OpenMP target testing pipeline
- [x] Enable TBB for the most current Intel compiler  (TBB removed)

**Comment by kab163** [comment]
We also talked about 
- updating the compilers that are used in our specs
- using the batch queue instead of debug (and maybe skip any unnecessary stages in the script)
- adding more "date" commands to the script
- switching to ruby instead of quartz

Just adding that in case we don't have it written down anywhere.

**Comment by rhornung67** [comment]
Thanks @kab163. I added the date command task to the list in this issue. The others are covered in these issues: https://github.com/LLNL/RAJA/issues/985 and https://github.com/LLNL/RAJA/issues/984

**Comment by kab163** [comment]
Ah cool! There's also the concern of the 'disk quota' continuing to exceed capacity. Though I think this would be addressed by the 4th item (using a service account).

**Comment by rhornung67** [comment]
All items have been consolidated in the list of this issue description as well as items in other related issues, which have been closed since this issue supercedes.

**Comment by rhornung67** [comment]
Superseded by https://github.com/LLNL/RAJA/issues/1335
