### ISSUE TITLE
No Resources support for kernel

### ISSUE THREAD

**Issue by corbett5** [LLNL/RAJA#990]
I'm sure this is on the radar but I don't see any related issues or PRs.

**Comment by mdavis36** [comment]
This was actually merged into develop a few days ago #966.

**Comment by corbett5** [comment]
Oh sick! So I can just pass a resource as the first argument, just like `forall`?

**Comment by mdavis36** [comment]
Yep should work just the same, it will now also return a `resource::Event` if you need. `example/resource-kernel.cpp` shows how to launch a bunch of kernels asynchronously with this feature.

**Comment by corbett5** [comment]
Great, well now I have an excellent reason to update RAJA.
