### ISSUE TITLE
RAJA::TypedListSegment from iteration spaces tutorial doesn't compile

### ISSUE THREAD

**Issue by mlohry** [LLNL/RAJA#995]
https://github.com/LLNL/RAJA/blob/main/docs/sphinx/user_guide/feature/iteration_spaces.rst

```
// Create a vector holding some integer index values
std::vector<int> idx = {0, 2, 3, 4, 7, 8, 9, 53};

// Create list segment with these loop indices
RAJA::TypedListSegment<int> idx_list( &idx[0], static_cast<int>(idx.size()) );
```

This code from the tutorial fails to compile with error
```
error: no matching constructor for initialization of 'RAJA::TypedListSegment<int>'
RAJA::TypedListSegment<int> idx_list( &idx[0], static_cast<int>(idx.size()) );
```

**Comment by rhornung67** [comment]
@mlohry Thanks for catching this. We recently deprecated the the ctor for the ListSegment to make it more robust and runtime configurable. I forgot to update the docs to reflect this. I will fix it ASAP.

**Comment by rhornung67** [comment]
@mlohry Documentation has been fixed in develop branch and will appear in next RAJA release in a few weeks.
